/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create the first organisation and owner account
         * @description Only allowed while the server has no users.
         */
        post: operations["setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        /** @description Requires admin. */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["userId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch: operations["updateUser"];
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTokens"];
        put?: never;
        post: operations["createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: components["parameters"]["tokenId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{projectId}/targets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["listTargets"];
        put?: never;
        post: operations["createTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/{targetId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetId: components["parameters"]["targetId"];
            };
            cookie?: never;
        };
        get: operations["getTarget"];
        put?: never;
        post?: never;
        delete: operations["deleteTarget"];
        options?: never;
        head?: never;
        patch: operations["updateTarget"];
        trace?: never;
    };
    "/targets/{targetId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetId: components["parameters"]["targetId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check the ownership token for a public target */
        post: operations["verifyTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["listSecrets"];
        put: operations["putSecret"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/secrets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
                name: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSecret"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["listScenarios"];
        put?: never;
        post: operations["createScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenarioId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: components["parameters"]["scenarioId"];
            };
            cookie?: never;
        };
        get: operations["getScenario"];
        put?: never;
        post?: never;
        delete: operations["deleteScenario"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenarioId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: components["parameters"]["scenarioId"];
            };
            cookie?: never;
        };
        get: operations["listScenarioVersions"];
        put?: never;
        post: operations["createScenarioVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenarioId}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: components["parameters"]["scenarioId"];
                version: number;
            };
            cookie?: never;
        };
        get: operations["getScenarioVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["listRuns"];
        put?: never;
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop gracefully; in-flight iterations may finish */
        post: operations["stopRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/kill": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kill switch for one run; all load stops immediately */
        post: operations["killRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/kill-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kill switch for every active run in the organisation */
        post: operations["killAllRuns"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/live": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        /**
         * Live metrics as server-sent events
         * @description Emits `point` events (a timeline Point per interval), `status`
         *     events when the run changes state, and `event` events for worker
         *     and safety events. Ends after the run completes.
         */
        get: operations["streamRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        get: operations["getRunTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/report": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        get: operations["getRunReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @example not_found */
                code: string;
                message: string;
                details?: string[];
            };
        };
        VersionInfo: {
            version: string;
            commit: string;
            setupRequired: boolean;
        };
        /** @enum {string} */
        Role: "owner" | "admin" | "editor" | "runner" | "viewer";
        SetupRequest: {
            organisation: string;
            name: string;
            /** Format: email */
            email: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        Session: {
            user: components["schemas"]["Me"];
            /** Format: date-time */
            expiresAt: string;
        };
        Me: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
            role: components["schemas"]["Role"];
            /** Format: uuid */
            orgId: string;
            orgName: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastLoginAt?: string | null;
        };
        UserCreate: {
            /** Format: email */
            email: string;
            name: string;
            role: components["schemas"]["Role"];
            password: string;
        };
        Token: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description First characters of the token */
            prefix: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt?: string | null;
            /** Format: date-time */
            expiresAt?: string | null;
        };
        TokenCreate: {
            name: string;
            role?: components["schemas"]["Role"];
            expiresInDays?: number;
        };
        TokenCreated: components["schemas"]["Token"] & {
            /** @description The full token. Shown once. */
            secret: string;
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string;
            /** Format: date-time */
            createdAt: string;
        };
        ProjectCreate: {
            name: string;
            description?: string;
        };
        Caps: {
            /** @description Iterations per second */
            maxRate?: number;
            maxVUs?: number;
            maxDurationSeconds?: number;
        };
        Target: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            name: string;
            baseURL: string;
            /** @description Loopback or private network; needs no verification. */
            private: boolean;
            verified: boolean;
            /** Format: date-time */
            verifiedAt?: string | null;
            verificationMethod?: string | null;
            /** @description Publish as a DNS TXT record `stampede-verify=<token>` or at /.well-known/stampede-verify.txt */
            verificationToken: string;
            allowHosts?: string[];
            caps: components["schemas"]["Caps"];
            /** Format: date-time */
            createdAt: string;
        };
        TargetCreate: {
            name: string;
            baseURL: string;
            allowHosts?: string[];
            caps?: components["schemas"]["Caps"];
        };
        Secret: {
            name: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SecretPut: {
            name: string;
            value: string;
        };
        Validation: {
            valid: boolean;
            problems: string[];
            plan?: components["schemas"]["PlanSummary"];
        };
        PlanSummary: {
            executor: string;
            mode: string;
            shape?: string;
            peak: number;
            durationSeconds: number;
            journeys: number;
            steps: number;
        };
        Scenario: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            name: string;
            description?: string;
            tags: string[];
            latestVersion: components["schemas"]["ScenarioVersion"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ScenarioVersion: {
            /** Format: uuid */
            scenarioId: string;
            version: number;
            yaml: string;
            message?: string;
            createdBy?: string | null;
            /** Format: date-time */
            createdAt: string;
            plan?: components["schemas"]["PlanSummary"];
        };
        ScenarioVersionCreate: {
            yaml: string;
            message?: string;
        };
        /** @enum {string} */
        RunStatus: "scheduling" | "starting" | "running" | "stopping" | "analyzing" | "completed" | "aborted" | "failed";
        RunOverrides: {
            shape?: string;
            /** @enum {string} */
            mode?: "vus" | "rate";
            vus?: number;
            /** @example 100/s */
            rate?: string;
            /** @example 5m */
            duration?: string;
            start?: string;
            max?: string;
        };
        RunCreate: {
            /** Format: uuid */
            scenarioId: string;
            /** @description Defaults to the latest */
            version?: number;
            /** Format: uuid */
            targetId: string;
            overrides?: components["schemas"]["RunOverrides"];
            env?: {
                [key: string]: string;
            };
            /** @description 0 uses every connected worker */
            workers?: number;
            note?: string;
        };
        Run: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            scenarioId: string;
            scenarioName?: string;
            scenarioVersion: number;
            /** Format: uuid */
            targetId: string;
            targetURL?: string;
            status: components["schemas"]["RunStatus"];
            /** @enum {string|null} */
            verdict?: "pass" | "fail" | "generator-limited" | "no-targets" | null;
            stopReason?: string | null;
            error?: string | null;
            overrides?: components["schemas"]["RunOverrides"];
            plan?: components["schemas"]["PlanSummary"];
            workers?: number;
            note?: string;
            createdBy?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            endedAt?: string | null;
            summary?: components["schemas"]["RunSummary"];
        };
        RunSummary: {
            requests?: number;
            errorRate?: number;
            rps?: number;
            /** @description seconds */
            p95?: number;
            /** @description seconds */
            p99?: number;
        } | null;
        Point: {
            /** @description Seconds since start */
            t: number;
            rps: number;
            errorRate: number;
            p50: number;
            p95: number;
            p99: number;
            vus: number;
            planned: number;
            dropped: number;
            iterations?: number;
            schedLagP99?: number;
        };
        /** @description The full report; same format as `stampede run --json`. */
        Report: {
            [key: string]: unknown;
        };
        Worker: {
            id: string;
            name: string;
            region: string;
            version?: string;
            labels?: {
                [key: string]: string;
            };
            cpus?: number;
            memoryBytes?: number;
            /** @enum {string} */
            status: "idle" | "busy" | "saturated" | "lost";
            runId?: string | null;
            /** Format: date-time */
            connectedAt: string;
            /** Format: date-time */
            lastSeenAt: string;
        };
        AuditEntry: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            at: string;
            /** @description User email or token name */
            actor: string;
            /** @example run.start */
            action: string;
            subject?: string;
            details?: {
                [key: string]: unknown;
            };
            ip?: string;
        };
    };
    responses: {
        /** @description Not signed in or token invalid */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The caller's role does not allow this */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflicts with the current state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request is well-formed but invalid */
        Invalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many attempts */
        TooMany: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        userId: string;
        tokenId: string;
        projectId: string;
        targetId: string;
        scenarioId: string;
        runId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server version and setup state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
    setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Owner created and signed in */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Invalid"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in; sets the session cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooMany"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    current: string;
                    new: string;
                };
            };
        };
        responses: {
            /** @description Changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Invalid"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members of the organisation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Invalid"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["userId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["userId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    role?: components["schemas"]["Role"];
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's API tokens (secrets are never returned) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"][];
                };
            };
        };
    };
    createToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenCreate"];
            };
        };
        responses: {
            /** @description Created. The secret is shown only in this response. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenCreated"];
                };
            };
            422: components["responses"]["Invalid"];
        };
    };
    deleteToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: components["parameters"]["tokenId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Invalid"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted with everything in it */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listTargets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Targets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"][];
                };
            };
        };
    };
    createTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
            422: components["responses"]["Invalid"];
        };
    };
    getTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetId: components["parameters"]["targetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Target */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetId: components["parameters"]["targetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetId: components["parameters"]["targetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetCreate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    verifyTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetId: components["parameters"]["targetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification state after the check */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listSecrets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Secret names (values are never returned) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Secret"][];
                };
            };
        };
    };
    putSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretPut"];
            };
        };
        responses: {
            /** @description Stored, encrypted at rest */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Secret"];
                };
            };
            422: components["responses"]["Invalid"];
        };
    };
    deleteSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    validateScenario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    yaml: string;
                };
            };
        };
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Validation"];
                };
            };
        };
    };
    listScenarios: {
        parameters: {
            query?: {
                tag?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenarios with their latest version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scenario"][];
                };
            };
        };
    };
    createScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioVersionCreate"];
            };
        };
        responses: {
            /** @description Created with version 1 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scenario"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Invalid"];
        };
    };
    getScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: components["parameters"]["scenarioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario with its latest version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scenario"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: components["parameters"]["scenarioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listScenarioVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: components["parameters"]["scenarioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All versions, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioVersion"][];
                };
            };
        };
    };
    createScenarioVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: components["parameters"]["scenarioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioVersionCreate"];
            };
        };
        responses: {
            /** @description New version saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioVersion"];
                };
            };
            422: components["responses"]["Invalid"];
        };
    };
    getScenarioVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: components["parameters"]["scenarioId"];
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioVersion"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                scenarioId?: string;
                limit?: number;
                /** @description Return runs created before this time (pagination). */
                before?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runs, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Run accepted and scheduled */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Invalid"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    stopRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stopping */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    killRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Killed */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    killAllRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runs that were killed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        killed: string[];
                    };
                };
            };
        };
    };
    streamRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getRunTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-interval points recorded so far */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Point"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getRunReport: {
        parameters: {
            query?: {
                format?: "json" | "html" | "junit" | "markdown";
            };
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The report. JSON follows the `stampede run --json` format. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                    "text/html": string;
                    "application/xml": string;
                    "text/markdown": string;
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listWorkers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connected workers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Worker"][];
                };
            };
        };
    };
    listAudit: {
        parameters: {
            query?: {
                limit?: number;
                before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit log, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
}
