/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create the first organisation and owner account
         * @description Only allowed while the server has no users.
         */
        post: operations["setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        /** @description Requires admin. */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["userId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch: operations["updateUser"];
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTokens"];
        put?: never;
        post: operations["createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: components["parameters"]["tokenId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{projectId}/targets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["listTargets"];
        put?: never;
        post: operations["createTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/targets/{targetId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetId: components["parameters"]["targetId"];
            };
            cookie?: never;
        };
        get: operations["getTarget"];
        put?: never;
        post?: never;
        delete: operations["deleteTarget"];
        options?: never;
        head?: never;
        patch: operations["updateTarget"];
        trace?: never;
    };
    "/targets/{targetId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetId: components["parameters"]["targetId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check the ownership token for a public target */
        post: operations["verifyTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["listSecrets"];
        put: operations["putSecret"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/secrets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
                name: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSecret"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["listScenarios"];
        put?: never;
        post: operations["createScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenarioId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: components["parameters"]["scenarioId"];
            };
            cookie?: never;
        };
        get: operations["getScenario"];
        put?: never;
        post?: never;
        delete: operations["deleteScenario"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenarioId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: components["parameters"]["scenarioId"];
            };
            cookie?: never;
        };
        get: operations["listScenarioVersions"];
        put?: never;
        post: operations["createScenarioVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenarioId}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: components["parameters"]["scenarioId"];
                version: number;
            };
            cookie?: never;
        };
        get: operations["getScenarioVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["listRuns"];
        put?: never;
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop gracefully; in-flight iterations may finish */
        post: operations["stopRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/kill": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kill switch for one run; all load stops immediately */
        post: operations["killRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/kill-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kill switch for every active run in the organisation */
        post: operations["killAllRuns"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/live": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        /**
         * Live metrics as server-sent events
         * @description Emits `point` events (a timeline Point per interval), `status`
         *     events when the run changes state, and `event` events for worker
         *     and safety events. Ends after the run completes.
         */
        get: operations["streamRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        get: operations["getRunTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/report": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        get: operations["getRunReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** AI providers configured for the organisation (keys are never returned) */
        get: operations["listAIProviders"];
        put?: never;
        /**
         * Create or replace an AI provider by name
         * @description AI journey generation is optional and bring-your-own-key. The key is
         *     encrypted with the server's master key and never returned. Omit
         *     `apiKey` when replacing a provider to keep its stored key. Needs the
         *     admin role.
         */
        post: operations["putAIProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/providers/{providerId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAIProvider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/ai/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        get: operations["listAIJobs"];
        put?: never;
        /**
         * Generate a scenario with an AI model (asynchronous)
         * @description Starts a generation job: understand the inputs, draft a scenario,
         *     check it statically, dry-run each journey once with one user against
         *     the target, and repair failures (up to `maxRepairs` rounds). Recorded
         *     traffic is redacted before it reaches the provider. The result is a
         *     proposal; nothing is saved until `POST /ai/jobs/{jobId}/approve`.
         *     Refused with 429 when the organisation's AI token use this month
         *     has reached the provider's cap.
         */
        post: operations["createAIJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/narrative": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write an AI summary of a finished run's report
         * @description Asks the organisation's AI provider for a summary of the report.
         *     Every claim cites the report figures it rests on and is labelled
         *     measured or suspected; claims that cite unknown figures, or state
         *     numbers the cited figures do not contain, are dropped. Only the
         *     report's aggregate figures are sent, with error messages redacted.
         *     The narrative is saved into the report, so the HTML and Markdown
         *     downloads include it, and replaces any earlier one. Refused with
         *     429 when the organisation's AI token use this month has reached
         *     the provider's cap.
         */
        post: operations["createRunNarrative"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        /** Job status, stage, token usage, proposal, dry-run traces, problems and diff */
        get: operations["getAIJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/jobs/{jobId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save the proposal as a new scenario or a new scenario version
         * @description A person approves a finished job by saving its proposal: as a new
         *     version of `scenarioId` (default: the scenario the job compared
         *     against), otherwise as a new scenario. Jobs with flagged journeys
         *     need `allowUnvalidated`. Needs the editor role and is audited.
         */
        post: operations["approveAIJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Integrations configured for the organisation (tokens are never returned) */
        get: operations["listIntegrations"];
        put?: never;
        /**
         * Add a named Prometheus or traces integration
         * @description Scenarios run on the server refer to integrations by name
         *     (`observe: { prometheus: { integration: <name>, queries: ... } }`),
         *     so the server only ever contacts URLs an admin configured here.
         *     A Prometheus bearer token is encrypted with the server's master key
         *     and never returned. Needs the admin role and is audited.
         */
        post: operations["createIntegration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/{integrationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                integrationId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteIntegration"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notification channels of the organisation (URLs and secrets are never returned) */
        get: operations["listNotificationChannels"];
        put?: never;
        /**
         * Add a webhook, Slack or Discord channel
         * @description The destination URL is encrypted with the server's master key. A
         *     generic webhook signs each body with HMAC-SHA256 in the
         *     `X-Stampede-Signature` header; its secret is generated when not
         *     given and returned only in this response. Destinations on private,
         *     loopback or link-local addresses are refused unless
         *     `allowPrivate` is set. Needs the admin role and is audited.
         */
        post: operations["createNotificationChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/channels/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["channelId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteNotificationChannel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/channels/{channelId}/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["channelId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a test notification now (one attempt, no retries) */
        post: operations["testNotificationChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/channels/{channelId}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["channelId"];
            };
            cookie?: never;
        };
        /** The most recent delivery attempts of a channel, newest first */
        get: operations["listNotificationDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @example not_found */
                code: string;
                message: string;
                details?: string[];
            };
        };
        VersionInfo: {
            version: string;
            commit: string;
            setupRequired: boolean;
        };
        /** @enum {string} */
        Role: "owner" | "admin" | "editor" | "runner" | "viewer";
        SetupRequest: {
            organisation: string;
            name: string;
            /** Format: email */
            email: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        Session: {
            user: components["schemas"]["Me"];
            /** Format: date-time */
            expiresAt: string;
        };
        Me: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
            role: components["schemas"]["Role"];
            /** Format: uuid */
            orgId: string;
            orgName: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastLoginAt?: string | null;
        };
        UserCreate: {
            /** Format: email */
            email: string;
            name: string;
            role: components["schemas"]["Role"];
            password: string;
        };
        Token: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description First characters of the token */
            prefix: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt?: string | null;
            /** Format: date-time */
            expiresAt?: string | null;
        };
        TokenCreate: {
            name: string;
            role?: components["schemas"]["Role"];
            expiresInDays?: number;
        };
        TokenCreated: components["schemas"]["Token"] & {
            /** @description The full token. Shown once. */
            secret: string;
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string;
            /** Format: date-time */
            createdAt: string;
        };
        ProjectCreate: {
            name: string;
            description?: string;
        };
        Caps: {
            /**
             * Format: double
             * @description Iterations per second
             */
            maxRate?: number;
            maxVUs?: number;
            maxDurationSeconds?: number;
        };
        Target: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            name: string;
            baseURL: string;
            /** @description Loopback or private network; needs no verification. */
            private: boolean;
            verified: boolean;
            /** Format: date-time */
            verifiedAt?: string | null;
            verificationMethod?: string | null;
            /** @description Publish as a DNS TXT record `stampede-verify=<token>` or at /.well-known/stampede-verify.txt */
            verificationToken: string;
            allowHosts?: string[];
            caps: components["schemas"]["Caps"];
            /** Format: date-time */
            createdAt: string;
        };
        TargetCreate: {
            name: string;
            baseURL: string;
            allowHosts?: string[];
            caps?: components["schemas"]["Caps"];
        };
        Secret: {
            name: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SecretPut: {
            name: string;
            value: string;
        };
        Validation: {
            valid: boolean;
            problems: string[];
            plan?: components["schemas"]["PlanSummary"];
        };
        PlanSummary: {
            executor: string;
            mode: string;
            shape?: string;
            /** Format: double */
            peak: number;
            /** Format: double */
            durationSeconds: number;
            journeys: number;
            steps: number;
        };
        Scenario: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            name: string;
            description?: string;
            tags: string[];
            latestVersion: components["schemas"]["ScenarioVersion"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ScenarioVersion: {
            /** Format: uuid */
            scenarioId: string;
            version: number;
            yaml: string;
            message?: string;
            createdBy?: string | null;
            /** Format: date-time */
            createdAt: string;
            plan?: components["schemas"]["PlanSummary"];
        };
        ScenarioVersionCreate: {
            yaml: string;
            message?: string;
        };
        /** @enum {string} */
        RunStatus: "scheduling" | "starting" | "running" | "stopping" | "analyzing" | "completed" | "aborted" | "failed";
        RunOverrides: {
            shape?: string;
            /** @enum {string} */
            mode?: "vus" | "rate";
            vus?: number;
            /** @example 100/s */
            rate?: string;
            /** @example 5m */
            duration?: string;
            start?: string;
            max?: string;
        };
        RunCreate: {
            /** Format: uuid */
            scenarioId: string;
            /** @description Defaults to the latest */
            version?: number;
            /** Format: uuid */
            targetId: string;
            overrides?: components["schemas"]["RunOverrides"];
            env?: {
                [key: string]: string;
            };
            /** @description 0 uses every connected worker */
            workers?: number;
            note?: string;
        };
        Run: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            scenarioId: string;
            scenarioName?: string;
            scenarioVersion: number;
            /** Format: uuid */
            targetId: string;
            targetURL?: string;
            status: components["schemas"]["RunStatus"];
            /** @enum {string|null} */
            verdict?: "pass" | "fail" | "generator-limited" | "no-targets" | null;
            stopReason?: string | null;
            error?: string | null;
            overrides?: components["schemas"]["RunOverrides"];
            plan?: components["schemas"]["PlanSummary"];
            workers?: number;
            note?: string;
            createdBy?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            endedAt?: string | null;
            summary?: components["schemas"]["RunSummary"];
        };
        RunSummary: {
            requests?: number;
            /** Format: double */
            errorRate?: number;
            /** Format: double */
            rps?: number;
            /**
             * Format: double
             * @description seconds
             */
            p95?: number;
            /**
             * Format: double
             * @description seconds
             */
            p99?: number;
        } | null;
        Point: {
            /**
             * Format: double
             * @description Seconds since start
             */
            t: number;
            /** Format: double */
            rps: number;
            /** Format: double */
            errorRate: number;
            /** Format: double */
            p50: number;
            /** Format: double */
            p95: number;
            /** Format: double */
            p99: number;
            vus: number;
            /** Format: double */
            planned: number;
            dropped: number;
            iterations?: number;
            /** Format: double */
            schedLagP99?: number;
        };
        /** @description The full report; same format as `stampede run --json`. */
        Report: {
            [key: string]: unknown;
        };
        Worker: {
            id: string;
            name: string;
            region: string;
            version?: string;
            labels?: {
                [key: string]: string;
            };
            cpus?: number;
            memoryBytes?: number;
            /** @enum {string} */
            status: "idle" | "busy" | "saturated" | "lost";
            runId?: string | null;
            /** Format: date-time */
            connectedAt: string;
            /** Format: date-time */
            lastSeenAt: string;
        };
        AuditEntry: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            at: string;
            /** @description User email or token name */
            actor: string;
            /** @example run.start */
            action: string;
            subject?: string;
            details?: {
                [key: string]: unknown;
            };
            ip?: string;
        };
        /** @enum {string} */
        AIProviderKind: "anthropic" | "openai" | "gemini" | "ollama" | "openai-compatible";
        AIProvider: {
            /** Format: uuid */
            id: string;
            name: string;
            kind: components["schemas"]["AIProviderKind"];
            model: string;
            baseURL?: string;
            /** @description Whether an API key is stored. The key itself is never returned. */
            hasKey: boolean;
            /**
             * Format: int64
             * @description Jobs are refused once the organisation's AI token use this calendar month (UTC) reaches this cap.
             */
            monthlyTokenCap: number;
            /** Format: int64 */
            usedTokensThisMonth: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AIProviderPut: {
            /** @default default */
            name: string;
            kind: components["schemas"]["AIProviderKind"];
            /** @description Required except for anthropic (default claude-sonnet-5-5). */
            model?: string;
            /** @description API base URL; required for openai-compatible. */
            baseURL?: string;
            /** @description Stored encrypted; omit to keep the current key. */
            apiKey?: string;
            /**
             * Format: int64
             * @description Default 2000000.
             */
            monthlyTokenCap?: number;
        };
        AIJobCreate: {
            /**
             * Format: uuid
             * @description Defaults to the organisation's only provider
             */
            providerId?: string;
            description?: string;
            /** @description OpenAPI 3.x document (YAML or JSON) */
            openapi?: string;
            /** @description HAR recording (JSON) */
            har?: string;
            /** @description Web server access log */
            accessLog?: string;
            /**
             * Format: uuid
             * @description Required for the dry run.
             */
            targetId?: string;
            /**
             * Format: uuid
             * @description Existing scenario to compare the proposal with.
             */
            scenarioId?: string;
            /** @default true */
            dryRun: boolean;
            /** @default 3 */
            maxRepairs: number;
        };
        AIUsage: {
            /** Format: int64 */
            inputTokens: number;
            /** Format: int64 */
            outputTokens: number;
        };
        NarrativeCreate: {
            /**
             * Format: uuid
             * @description Provider to use; default the only one, or the one named "default".
             */
            providerId?: string;
        };
        NarrativeResult: {
            narrative: components["schemas"]["Narrative"];
            usage: components["schemas"]["AIUsage"];
        };
        Narrative: {
            summary: string;
            model?: string;
            claims: components["schemas"]["NarrativeClaim"][];
            /** @description The report figures the claims cite. */
            facts?: components["schemas"]["NarrativeFact"][];
        };
        NarrativeClaim: {
            text: string;
            /** @enum {string} */
            label: "measured" | "suspected";
            /** @description Ids of the facts the claim rests on. */
            refs: string[];
        };
        NarrativeFact: {
            id: string;
            text: string;
            /** @description The report section that shows it. */
            where: string;
        };
        /**
         * @description succeeded means every journey passed its dry run; needs_review means some journeys are flagged.
         * @enum {string}
         */
        AIJobStatus: "queued" | "running" | "succeeded" | "needs_review" | "failed";
        AIProblem: {
            journey?: string;
            message: string;
            /** @description The proposal cannot be used while this problem remains. */
            fatal?: boolean;
        };
        AICheck: {
            name: string;
            ok: boolean;
            detail?: string;
        };
        /** @description One request of a dry run. Bodies are truncated; secrets and personal data are redacted. */
        AIStepTrace: {
            step: string;
            method?: string;
            url?: string;
            requestHeaders?: {
                [key: string]: string;
            };
            requestBody?: string;
            status?: number;
            responseHeaders?: {
                [key: string]: string;
            };
            responseBody?: string;
            /** Format: double */
            durationMs: number;
            extracted?: {
                [key: string]: string;
            };
            checks?: components["schemas"]["AICheck"][];
            ok: boolean;
            error?: string;
            note?: string;
        };
        AITrace: {
            pass: number;
            branches?: string[];
            ok: boolean;
            error?: string;
            steps: components["schemas"]["AIStepTrace"][];
        };
        AIJourney: {
            name: string;
            /** @enum {string} */
            status: "passed" | "flagged" | "not-run";
            /** @description Dry runs of this journey across repair rounds */
            attempts: number;
            problems?: string[];
            traces: components["schemas"]["AITrace"][];
        };
        AIJobSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            status: components["schemas"]["AIJobStatus"];
            /** @description understand, draft, static-check, dry-run, repair or done */
            stage: string;
            providerKind: string;
            model: string;
            usage: components["schemas"]["AIUsage"];
            dryRun: boolean;
            error?: string;
            createdBy?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            finishedAt?: string | null;
            /** Format: date-time */
            approvedAt?: string | null;
        };
        AIJob: components["schemas"]["AIJobSummary"] & {
            /** @description Repair round (0 is the first draft) */
            round: number;
            /** Format: uuid */
            targetId?: string | null;
            /** Format: uuid */
            scenarioId?: string | null;
            /** @description The proposed scenario */
            yaml?: string;
            /** @description Unified diff against scenarioId's latest version */
            diff?: string;
            problems: components["schemas"]["AIProblem"][];
            journeys: components["schemas"]["AIJourney"][];
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: uuid */
            approvedScenarioId?: string | null;
            approvedVersion?: number | null;
        };
        AIJobApprove: {
            /**
             * Format: uuid
             * @description Save as a new version of this scenario
             */
            scenarioId?: string;
            message?: string;
            /**
             * @description Approve even though some journeys are flagged
             * @default false
             */
            allowUnvalidated: boolean;
        };
        AIJobApproval: {
            scenario: components["schemas"]["Scenario"];
            version: number;
        };
        /** @enum {string} */
        IntegrationKind: "prometheus" | "traces";
        Integration: {
            /** Format: uuid */
            id: string;
            name: string;
            kind: components["schemas"]["IntegrationKind"];
            /** @description Prometheus base URL, or for traces a link template containing {traceId}. */
            url: string;
            /** @description Whether a bearer token is stored. The token itself is never returned. */
            hasToken: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        IntegrationCreate: {
            name: string;
            kind: components["schemas"]["IntegrationKind"];
            /**
             * @description prometheus: the base URL, e.g. http://prometheus:9090. traces: a link
             *     template containing {traceId}, e.g. https://jaeger.example.com/trace/{traceId}.
             */
            url: string;
            /** @description Prometheus only. Stored encrypted. */
            bearerToken?: string;
        };
        /** @enum {string} */
        NotificationKind: "webhook" | "slack" | "discord";
        /** @enum {string} */
        NotificationEvent: "run.finished" | "run.target_failed" | "run.killed";
        NotificationChannel: {
            /** Format: uuid */
            id: string;
            name: string;
            kind: components["schemas"]["NotificationKind"];
            events: components["schemas"]["NotificationEvent"][];
            /** @description Deliveries may reach private, loopback and link-local addresses. */
            allowPrivate: boolean;
            /** @description The destination's scheme and host only, e.g. https://hooks.slack.com */
            urlHint: string;
            /** @description Whether bodies are signed (generic webhooks). */
            hasSecret: boolean;
            /** Format: date-time */
            createdAt: string;
            lastDelivery?: components["schemas"]["NotificationDelivery"];
        };
        NotificationChannelCreate: {
            name: string;
            kind: components["schemas"]["NotificationKind"];
            /** @description Webhook URL. Stored encrypted and never returned. */
            url: string;
            /** @description Default all events. */
            events?: components["schemas"]["NotificationEvent"][];
            /** @default false */
            allowPrivate: boolean;
            /** @description Webhook signing secret. Generated when omitted; ignored for Slack and Discord. */
            secret?: string;
        };
        NotificationChannelCreated: {
            channel: components["schemas"]["NotificationChannel"];
            /** @description The webhook signing secret. Shown only once. */
            secret?: string;
        };
        NotificationDelivery: {
            /** Format: int64 */
            id: number;
            /**
             * Format: uuid
             * @description Same for every attempt of one delivery (X-Stampede-Delivery).
             */
            deliveryId: string;
            /** @example run.finished */
            event: string;
            /** Format: uuid */
            runId?: string | null;
            attempt: number;
            ok: boolean;
            /** @description HTTP status; 0 when no response was received. */
            statusCode: number;
            error: string;
            durationMs: number;
            /** Format: date-time */
            at: string;
        };
    };
    responses: {
        /** @description Not signed in or token invalid */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The caller's role does not allow this */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflicts with the current state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request is well-formed but invalid */
        Invalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many attempts */
        TooMany: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        userId: string;
        tokenId: string;
        projectId: string;
        targetId: string;
        scenarioId: string;
        runId: string;
        channelId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server version and setup state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
    setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Owner created and signed in */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Invalid"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in; sets the session cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooMany"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    current: string;
                    new: string;
                };
            };
        };
        responses: {
            /** @description Changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Invalid"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members of the organisation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Invalid"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["userId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["userId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    role?: components["schemas"]["Role"];
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's API tokens (secrets are never returned) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"][];
                };
            };
        };
    };
    createToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenCreate"];
            };
        };
        responses: {
            /** @description Created. The secret is shown only in this response. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenCreated"];
                };
            };
            422: components["responses"]["Invalid"];
        };
    };
    deleteToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: components["parameters"]["tokenId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Invalid"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted with everything in it */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listTargets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Targets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"][];
                };
            };
        };
    };
    createTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
            422: components["responses"]["Invalid"];
        };
    };
    getTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetId: components["parameters"]["targetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Target */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetId: components["parameters"]["targetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetId: components["parameters"]["targetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetCreate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    verifyTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                targetId: components["parameters"]["targetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification state after the check */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listSecrets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Secret names (values are never returned) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Secret"][];
                };
            };
        };
    };
    putSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretPut"];
            };
        };
        responses: {
            /** @description Stored, encrypted at rest */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Secret"];
                };
            };
            422: components["responses"]["Invalid"];
        };
    };
    deleteSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    validateScenario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    yaml: string;
                };
            };
        };
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Validation"];
                };
            };
        };
    };
    listScenarios: {
        parameters: {
            query?: {
                tag?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenarios with their latest version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scenario"][];
                };
            };
        };
    };
    createScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioVersionCreate"];
            };
        };
        responses: {
            /** @description Created with version 1 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scenario"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["Invalid"];
        };
    };
    getScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: components["parameters"]["scenarioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario with its latest version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scenario"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: components["parameters"]["scenarioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listScenarioVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: components["parameters"]["scenarioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All versions, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioVersion"][];
                };
            };
        };
    };
    createScenarioVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: components["parameters"]["scenarioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioVersionCreate"];
            };
        };
        responses: {
            /** @description New version saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioVersion"];
                };
            };
            422: components["responses"]["Invalid"];
        };
    };
    getScenarioVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: components["parameters"]["scenarioId"];
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioVersion"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                scenarioId?: string;
                limit?: number;
                /** @description Return runs created before this time (pagination). */
                before?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runs, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Run accepted and scheduled */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Invalid"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    stopRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stopping */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    killRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Killed */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    killAllRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runs that were killed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        killed: string[];
                    };
                };
            };
        };
    };
    streamRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getRunTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-interval points recorded so far */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Point"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getRunReport: {
        parameters: {
            query?: {
                format?: "json" | "html" | "junit" | "markdown";
            };
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The report. JSON follows the `stampede run --json` format. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                    "text/html": string;
                    "application/xml": string;
                    "text/markdown": string;
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listWorkers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connected workers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Worker"][];
                };
            };
        };
    };
    listAudit: {
        parameters: {
            query?: {
                limit?: number;
                before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit log, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listAIProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Providers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIProvider"][];
                };
            };
        };
    };
    putAIProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIProviderPut"];
            };
        };
        responses: {
            /** @description Replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIProvider"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIProvider"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Invalid"];
        };
    };
    deleteAIProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAIJobs: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generation jobs, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIJobSummary"][];
                };
            };
        };
    };
    createAIJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIJobCreate"];
            };
        };
        responses: {
            /** @description Job accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIJob"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Invalid"];
            /** @description Monthly AI token cap reached, or too many jobs queued */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createRunNarrative: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["runId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NarrativeCreate"];
            };
        };
        responses: {
            /** @description The narrative, now part of the report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NarrativeResult"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Invalid"];
            /** @description Monthly AI token cap reached */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The AI provider failed or returned nothing usable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAIJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIJob"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    approveAIJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIJobApprove"];
            };
        };
        responses: {
            /** @description Saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIJobApproval"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Invalid"];
        };
    };
    listIntegrations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Integrations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Integration"][];
                };
            };
        };
    };
    createIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntegrationCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Integration"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Invalid"];
        };
    };
    deleteIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                integrationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listNotificationChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationChannel"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createNotificationChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationChannelCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationChannelCreated"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Invalid"];
        };
    };
    deleteNotificationChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["channelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    testNotificationChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["channelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The attempt, also recorded in the delivery log */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationDelivery"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listNotificationDeliveries: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                channelId: components["parameters"]["channelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attempts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationDelivery"][];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
