// Package store is Stampede's PostgreSQL (and TimescaleDB) persistence:
// connection pool, embedded migrations and typed queries generated by sqlc
// from internal/store/queries.
package store

import (
	"context"
	"database/sql"
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"log/slog"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"

	"github.com/Ivan825/Stampede/internal/store/db"
)

//go:embed migrations/*.sql
var migrations embed.FS

// Store wraps a connection pool and the generated queries.
type Store struct {
	Pool *pgxpool.Pool
	*db.Queries
}

// Open connects to PostgreSQL and checks the connection.
func Open(ctx context.Context, url string) (*Store, error) {
	cfg, err := pgxpool.ParseConfig(url)
	if err != nil {
		return nil, fmt.Errorf("database URL: %w", err)
	}
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, err
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("connect to database: %w", err)
	}
	return &Store{Pool: pool, Queries: db.New(pool)}, nil
}

// Close releases the pool.
func (s *Store) Close() { s.Pool.Close() }

// Migrate applies pending migrations. With dryRun it only reports them.
func (s *Store) Migrate(ctx context.Context, log *slog.Logger, dryRun bool) error {
	sqlDB := stdlib.OpenDBFromPool(s.Pool)
	defer sqlDB.Close()
	p, err := goose.NewProvider(goose.DialectPostgres, sqlDB, migrationsFS())
	if err != nil {
		return err
	}
	if dryRun {
		pending, err := p.HasPending(ctx)
		if err != nil {
			return err
		}
		cur, _ := p.GetDBVersion(ctx)
		log.Info("migration dry run", "current", cur, "pending", pending)
		return nil
	}
	res, err := p.Up(ctx)
	for _, r := range res {
		log.Info("migration applied", "version", r.Source.Version, "file", r.Source.Path, "took", r.Duration)
	}
	return err
}

// MigrationVersion reports the applied schema version.
func (s *Store) MigrationVersion(ctx context.Context) (int64, error) {
	sqlDB := stdlib.OpenDBFromPool(s.Pool)
	defer sqlDB.Close()
	p, err := goose.NewProvider(goose.DialectPostgres, sqlDB, migrationsFS())
	if err != nil {
		return 0, err
	}
	return p.GetDBVersion(ctx)
}

func migrationsFS() fs.FS {
	sub, err := fs.Sub(migrations, "migrations")
	if err != nil {
		panic(err) // the embedded directory always exists
	}
	return sub
}

// InTx runs fn in a transaction, committing when it returns nil.
func (s *Store) InTx(ctx context.Context, fn func(q *db.Queries) error) error {
	tx, err := s.Pool.BeginTx(ctx, pgx.TxOptions{})
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx) //nolint:errcheck // no-op after commit
	if err := fn(s.WithTx(tx)); err != nil {
		return err
	}
	return tx.Commit(ctx)
}

// InTxLocked is InTx holding a transaction-scoped advisory lock on key, so
// concurrent callers with the same key run one at a time.
func (s *Store) InTxLocked(ctx context.Context, key int64, fn func(q *db.Queries) error) error {
	tx, err := s.Pool.BeginTx(ctx, pgx.TxOptions{})
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx) //nolint:errcheck // no-op after commit
	if _, err := tx.Exec(ctx, "SELECT pg_advisory_xact_lock($1)", key); err != nil {
		return err
	}
	if err := fn(s.WithTx(tx)); err != nil {
		return err
	}
	return tx.Commit(ctx)
}

// IsNotFound reports whether err means no rows matched.
func IsNotFound(err error) bool {
	return errors.Is(err, pgx.ErrNoRows) || errors.Is(err, sql.ErrNoRows)
}

// IsUniqueViolation reports whether err is a unique constraint violation.
func IsUniqueViolation(err error) bool {
	var pe *pgconn.PgError
	return errors.As(err, &pe) && pe.Code == "23505"
}

// LeaderLockKey is the advisory lock held by the active server replica.
const LeaderLockKey = 7462

// Lock is a session-level advisory lock held on a dedicated connection.
type Lock struct {
	conn interface {
		Ping(context.Context) error
		Release()
	}
	key     int64
	release func()
}

// Alive reports whether the connection holding the lock still works. If it
// does not, the database has dropped the session and the lock with it.
func (l *Lock) Alive(ctx context.Context) error { return l.conn.Ping(ctx) }

// Release frees the lock.
func (l *Lock) Release() { l.release() }

// AdvisoryLock tries to take a session-level advisory lock on a dedicated
// connection, used for leader election between server replicas. It returns
// nil when another session holds the lock.
func (s *Store) AdvisoryLock(ctx context.Context, key int64) (*Lock, error) {
	conn, err := s.Pool.Acquire(ctx)
	if err != nil {
		return nil, err
	}
	var ok bool
	if err := conn.QueryRow(ctx, "SELECT pg_try_advisory_lock($1)", key).Scan(&ok); err != nil {
		conn.Release()
		return nil, err
	}
	if !ok {
		conn.Release()
		return nil, nil
	}
	return &Lock{conn: conn, key: key, release: func() {
		_, _ = conn.Exec(context.Background(), "SELECT pg_advisory_unlock($1)", key)
		conn.Release()
	}}, nil
}
