// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ai.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const aITokensSince = `-- name: AITokensSince :one
SELECT COALESCE(SUM(input_tokens + output_tokens), 0)::bigint AS tokens
FROM ai_jobs
WHERE org_id = $1 AND created_at >= $2
`

type AITokensSinceParams struct {
	OrgID     uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) AITokensSince(ctx context.Context, arg AITokensSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, aITokensSince, arg.OrgID, arg.CreatedAt)
	var tokens int64
	err := row.Scan(&tokens)
	return tokens, err
}

const claimAIJobApproval = `-- name: ClaimAIJobApproval :execrows
UPDATE ai_jobs SET approved_at = now()
WHERE id = $1 AND approved_at IS NULL AND status IN ('succeeded', 'needs_review')
`

func (q *Queries) ClaimAIJobApproval(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, claimAIJobApproval, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAIJob = `-- name: CreateAIJob :exec
INSERT INTO ai_jobs (id, org_id, project_id, provider_id, provider_kind, model, status, target_id, scenario_id, dry_run, inputs, created_by)
VALUES ($1, $2, $3, $4, $5, $6, 'queued', $7, $8, $9, $10, $11)
`

type CreateAIJobParams struct {
	ID           uuid.UUID
	OrgID        uuid.UUID
	ProjectID    uuid.UUID
	ProviderID   *uuid.UUID
	ProviderKind string
	Model        string
	TargetID     *uuid.UUID
	ScenarioID   *uuid.UUID
	DryRun       bool
	Inputs       json.RawMessage
	CreatedBy    *uuid.UUID
}

func (q *Queries) CreateAIJob(ctx context.Context, arg CreateAIJobParams) error {
	_, err := q.db.Exec(ctx, createAIJob,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.ProviderID,
		arg.ProviderKind,
		arg.Model,
		arg.TargetID,
		arg.ScenarioID,
		arg.DryRun,
		arg.Inputs,
		arg.CreatedBy,
	)
	return err
}

const createAIProvider = `-- name: CreateAIProvider :exec
INSERT INTO ai_providers (id, org_id, name, kind, model, base_url, ciphertext, wrapped_key, key_id, monthly_token_cap, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateAIProviderParams struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	Name            string
	Kind            string
	Model           string
	BaseUrl         string
	Ciphertext      []byte
	WrappedKey      []byte
	KeyID           *string
	MonthlyTokenCap int64
	CreatedBy       *uuid.UUID
}

func (q *Queries) CreateAIProvider(ctx context.Context, arg CreateAIProviderParams) error {
	_, err := q.db.Exec(ctx, createAIProvider,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Kind,
		arg.Model,
		arg.BaseUrl,
		arg.Ciphertext,
		arg.WrappedKey,
		arg.KeyID,
		arg.MonthlyTokenCap,
		arg.CreatedBy,
	)
	return err
}

const deleteAIProvider = `-- name: DeleteAIProvider :execrows
DELETE FROM ai_providers WHERE id = $1 AND org_id = $2
`

type DeleteAIProviderParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteAIProvider(ctx context.Context, arg DeleteAIProviderParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAIProvider, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failInterruptedAIJobs = `-- name: FailInterruptedAIJobs :execrows
UPDATE ai_jobs
SET status = 'failed', error = 'interrupted: the server stopped before the job finished', finished_at = now()
WHERE status IN ('queued', 'running')
`

func (q *Queries) FailInterruptedAIJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, failInterruptedAIJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishAIJob = `-- name: FinishAIJob :exec
UPDATE ai_jobs
SET status = $2, stage = $3, round = $4, yaml = $5, diff = $6, result = $7, error = $8,
    input_tokens = $9, output_tokens = $10, finished_at = now()
WHERE id = $1
`

type FinishAIJobParams struct {
	ID           uuid.UUID
	Status       string
	Stage        string
	Round        int32
	Yaml         string
	Diff         string
	Result       json.RawMessage
	Error        string
	InputTokens  int64
	OutputTokens int64
}

func (q *Queries) FinishAIJob(ctx context.Context, arg FinishAIJobParams) error {
	_, err := q.db.Exec(ctx, finishAIJob,
		arg.ID,
		arg.Status,
		arg.Stage,
		arg.Round,
		arg.Yaml,
		arg.Diff,
		arg.Result,
		arg.Error,
		arg.InputTokens,
		arg.OutputTokens,
	)
	return err
}

const getAIJob = `-- name: GetAIJob :one
SELECT id, org_id, project_id, provider_id, provider_kind, model, status, stage, round, target_id, scenario_id, dry_run, inputs, yaml, diff, result, error, input_tokens, output_tokens, created_by, created_at, started_at, finished_at, approved_at, approved_scenario_id, approved_version FROM ai_jobs WHERE id = $1 AND org_id = $2
`

type GetAIJobParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetAIJob(ctx context.Context, arg GetAIJobParams) (AiJob, error) {
	row := q.db.QueryRow(ctx, getAIJob, arg.ID, arg.OrgID)
	var i AiJob
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.ProviderID,
		&i.ProviderKind,
		&i.Model,
		&i.Status,
		&i.Stage,
		&i.Round,
		&i.TargetID,
		&i.ScenarioID,
		&i.DryRun,
		&i.Inputs,
		&i.Yaml,
		&i.Diff,
		&i.Result,
		&i.Error,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ApprovedAt,
		&i.ApprovedScenarioID,
		&i.ApprovedVersion,
	)
	return i, err
}

const getAIProvider = `-- name: GetAIProvider :one
SELECT id, org_id, name, kind, model, base_url, ciphertext, wrapped_key, key_id, monthly_token_cap, created_by, created_at, updated_at FROM ai_providers WHERE id = $1 AND org_id = $2
`

type GetAIProviderParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetAIProvider(ctx context.Context, arg GetAIProviderParams) (AiProvider, error) {
	row := q.db.QueryRow(ctx, getAIProvider, arg.ID, arg.OrgID)
	var i AiProvider
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Model,
		&i.BaseUrl,
		&i.Ciphertext,
		&i.WrappedKey,
		&i.KeyID,
		&i.MonthlyTokenCap,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAIProviderByName = `-- name: GetAIProviderByName :one
SELECT id, org_id, name, kind, model, base_url, ciphertext, wrapped_key, key_id, monthly_token_cap, created_by, created_at, updated_at FROM ai_providers WHERE org_id = $1 AND name = $2
`

type GetAIProviderByNameParams struct {
	OrgID uuid.UUID
	Name  string
}

func (q *Queries) GetAIProviderByName(ctx context.Context, arg GetAIProviderByNameParams) (AiProvider, error) {
	row := q.db.QueryRow(ctx, getAIProviderByName, arg.OrgID, arg.Name)
	var i AiProvider
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Model,
		&i.BaseUrl,
		&i.Ciphertext,
		&i.WrappedKey,
		&i.KeyID,
		&i.MonthlyTokenCap,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAIJobs = `-- name: ListAIJobs :many
SELECT id, project_id, status, stage, provider_kind, model, input_tokens, output_tokens, dry_run, error,
       created_by, created_at, finished_at, approved_at
FROM ai_jobs
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAIJobsParams struct {
	ProjectID uuid.UUID
	Limit     int32
}

type ListAIJobsRow struct {
	ID           uuid.UUID
	ProjectID    uuid.UUID
	Status       string
	Stage        string
	ProviderKind string
	Model        string
	InputTokens  int64
	OutputTokens int64
	DryRun       bool
	Error        string
	CreatedBy    *uuid.UUID
	CreatedAt    time.Time
	FinishedAt   *time.Time
	ApprovedAt   *time.Time
}

func (q *Queries) ListAIJobs(ctx context.Context, arg ListAIJobsParams) ([]ListAIJobsRow, error) {
	rows, err := q.db.Query(ctx, listAIJobs, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAIJobsRow{}
	for rows.Next() {
		var i ListAIJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Status,
			&i.Stage,
			&i.ProviderKind,
			&i.Model,
			&i.InputTokens,
			&i.OutputTokens,
			&i.DryRun,
			&i.Error,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.ApprovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIProviders = `-- name: ListAIProviders :many
SELECT id, org_id, name, kind, model, base_url, ciphertext, wrapped_key, key_id, monthly_token_cap, created_by, created_at, updated_at FROM ai_providers WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListAIProviders(ctx context.Context, orgID uuid.UUID) ([]AiProvider, error) {
	rows, err := q.db.Query(ctx, listAIProviders, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiProvider{}
	for rows.Next() {
		var i AiProvider
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Kind,
			&i.Model,
			&i.BaseUrl,
			&i.Ciphertext,
			&i.WrappedKey,
			&i.KeyID,
			&i.MonthlyTokenCap,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseAIJobApproval = `-- name: ReleaseAIJobApproval :exec
UPDATE ai_jobs SET approved_at = NULL WHERE id = $1 AND approved_scenario_id IS NULL
`

func (q *Queries) ReleaseAIJobApproval(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, releaseAIJobApproval, id)
	return err
}

const setAIJobApproved = `-- name: SetAIJobApproved :exec
UPDATE ai_jobs SET approved_scenario_id = $2, approved_version = $3 WHERE id = $1
`

type SetAIJobApprovedParams struct {
	ID                 uuid.UUID
	ApprovedScenarioID *uuid.UUID
	ApprovedVersion    *int32
}

func (q *Queries) SetAIJobApproved(ctx context.Context, arg SetAIJobApprovedParams) error {
	_, err := q.db.Exec(ctx, setAIJobApproved, arg.ID, arg.ApprovedScenarioID, arg.ApprovedVersion)
	return err
}

const startAIJob = `-- name: StartAIJob :exec
UPDATE ai_jobs SET status = 'running', started_at = now() WHERE id = $1 AND status = 'queued'
`

func (q *Queries) StartAIJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, startAIJob, id)
	return err
}

const updateAIJobProgress = `-- name: UpdateAIJobProgress :exec
UPDATE ai_jobs SET stage = $2, round = $3, input_tokens = $4, output_tokens = $5
WHERE id = $1 AND status = 'running'
`

type UpdateAIJobProgressParams struct {
	ID           uuid.UUID
	Stage        string
	Round        int32
	InputTokens  int64
	OutputTokens int64
}

func (q *Queries) UpdateAIJobProgress(ctx context.Context, arg UpdateAIJobProgressParams) error {
	_, err := q.db.Exec(ctx, updateAIJobProgress,
		arg.ID,
		arg.Stage,
		arg.Round,
		arg.InputTokens,
		arg.OutputTokens,
	)
	return err
}

const updateAIProvider = `-- name: UpdateAIProvider :exec
UPDATE ai_providers
SET kind = $3, model = $4, base_url = $5, ciphertext = $6, wrapped_key = $7, key_id = $8,
    monthly_token_cap = $9, updated_at = now()
WHERE id = $1 AND org_id = $2
`

type UpdateAIProviderParams struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	Kind            string
	Model           string
	BaseUrl         string
	Ciphertext      []byte
	WrappedKey      []byte
	KeyID           *string
	MonthlyTokenCap int64
}

func (q *Queries) UpdateAIProvider(ctx context.Context, arg UpdateAIProviderParams) error {
	_, err := q.db.Exec(ctx, updateAIProvider,
		arg.ID,
		arg.OrgID,
		arg.Kind,
		arg.Model,
		arg.BaseUrl,
		arg.Ciphertext,
		arg.WrappedKey,
		arg.KeyID,
		arg.MonthlyTokenCap,
	)
	return err
}
