// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: drift.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createDriftResult = `-- name: CreateDriftResult :exec
INSERT INTO drift_results (id, project_id, schedule_id, scenario_id, scenario_version, target_id, status, error, broken, result, spec, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateDriftResultParams struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	ScheduleID      *uuid.UUID
	ScenarioID      uuid.UUID
	ScenarioVersion int32
	TargetID        uuid.UUID
	Status          string
	Error           string
	Broken          []string
	Result          json.RawMessage
	Spec            json.RawMessage
	CreatedBy       *uuid.UUID
}

func (q *Queries) CreateDriftResult(ctx context.Context, arg CreateDriftResultParams) error {
	_, err := q.db.Exec(ctx, createDriftResult,
		arg.ID,
		arg.ProjectID,
		arg.ScheduleID,
		arg.ScenarioID,
		arg.ScenarioVersion,
		arg.TargetID,
		arg.Status,
		arg.Error,
		arg.Broken,
		arg.Result,
		arg.Spec,
		arg.CreatedBy,
	)
	return err
}

const getDriftResult = `-- name: GetDriftResult :one
SELECT d.id, d.project_id, d.schedule_id, d.scenario_id, d.scenario_version, d.target_id, d.status, d.error, d.broken, d.result, d.spec, d.repair_job_id, d.created_by, d.created_at, s.name AS scenario_name, t.base_url AS target_url, sc.name AS schedule_name
FROM drift_results d
JOIN projects p ON p.id = d.project_id
JOIN scenarios s ON s.id = d.scenario_id
JOIN targets t ON t.id = d.target_id
LEFT JOIN schedules sc ON sc.id = d.schedule_id
WHERE d.id = $1 AND p.org_id = $2
`

type GetDriftResultParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

type GetDriftResultRow struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	ScheduleID      *uuid.UUID
	ScenarioID      uuid.UUID
	ScenarioVersion int32
	TargetID        uuid.UUID
	Status          string
	Error           string
	Broken          []string
	Result          json.RawMessage
	Spec            json.RawMessage
	RepairJobID     *uuid.UUID
	CreatedBy       *uuid.UUID
	CreatedAt       time.Time
	ScenarioName    string
	TargetUrl       string
	ScheduleName    *string
}

func (q *Queries) GetDriftResult(ctx context.Context, arg GetDriftResultParams) (GetDriftResultRow, error) {
	row := q.db.QueryRow(ctx, getDriftResult, arg.ID, arg.OrgID)
	var i GetDriftResultRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ScheduleID,
		&i.ScenarioID,
		&i.ScenarioVersion,
		&i.TargetID,
		&i.Status,
		&i.Error,
		&i.Broken,
		&i.Result,
		&i.Spec,
		&i.RepairJobID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ScenarioName,
		&i.TargetUrl,
		&i.ScheduleName,
	)
	return i, err
}

const lastDriftSpec = `-- name: LastDriftSpec :one
SELECT spec FROM drift_results
WHERE schedule_id = $1 AND spec IS NOT NULL
ORDER BY created_at DESC
LIMIT 1
`

// The spec endpoints recorded by a schedule's latest check that fetched one.
func (q *Queries) LastDriftSpec(ctx context.Context, scheduleID *uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, lastDriftSpec, scheduleID)
	var spec json.RawMessage
	err := row.Scan(&spec)
	return spec, err
}

const listDriftResults = `-- name: ListDriftResults :many
SELECT d.id, d.project_id, d.schedule_id, d.scenario_id, d.scenario_version, d.target_id, d.status, d.error,
       d.broken, d.repair_job_id, d.created_at, s.name AS scenario_name, t.base_url AS target_url, sc.name AS schedule_name
FROM drift_results d
JOIN scenarios s ON s.id = d.scenario_id
JOIN targets t ON t.id = d.target_id
LEFT JOIN schedules sc ON sc.id = d.schedule_id
WHERE d.project_id = $1
  AND ($2::uuid IS NULL OR d.schedule_id = $2)
ORDER BY d.created_at DESC
LIMIT $3
`

type ListDriftResultsParams struct {
	ProjectID  uuid.UUID
	ScheduleID *uuid.UUID
	Lim        int32
}

type ListDriftResultsRow struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	ScheduleID      *uuid.UUID
	ScenarioID      uuid.UUID
	ScenarioVersion int32
	TargetID        uuid.UUID
	Status          string
	Error           string
	Broken          []string
	RepairJobID     *uuid.UUID
	CreatedAt       time.Time
	ScenarioName    string
	TargetUrl       string
	ScheduleName    *string
}

func (q *Queries) ListDriftResults(ctx context.Context, arg ListDriftResultsParams) ([]ListDriftResultsRow, error) {
	rows, err := q.db.Query(ctx, listDriftResults, arg.ProjectID, arg.ScheduleID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDriftResultsRow{}
	for rows.Next() {
		var i ListDriftResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ScheduleID,
			&i.ScenarioID,
			&i.ScenarioVersion,
			&i.TargetID,
			&i.Status,
			&i.Error,
			&i.Broken,
			&i.RepairJobID,
			&i.CreatedAt,
			&i.ScenarioName,
			&i.TargetUrl,
			&i.ScheduleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDriftRepairJob = `-- name: SetDriftRepairJob :exec
UPDATE drift_results SET repair_job_id = $2 WHERE id = $1
`

type SetDriftRepairJobParams struct {
	ID          uuid.UUID
	RepairJobID *uuid.UUID
}

func (q *Queries) SetDriftRepairJob(ctx context.Context, arg SetDriftRepairJobParams) error {
	_, err := q.db.Exec(ctx, setDriftRepairJob, arg.ID, arg.RepairJobID)
	return err
}
