// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: identity.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countOwners = `-- name: CountOwners :one
SELECT count(*) FROM memberships WHERE org_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :exec
INSERT INTO memberships (org_id, user_id, role) VALUES ($1, $2, $3)
`

type CreateMembershipParams struct {
	OrgID  uuid.UUID
	UserID uuid.UUID
	Role   string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const createOrg = `-- name: CreateOrg :exec
INSERT INTO orgs (id, name) VALUES ($1, $2)
`

type CreateOrgParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) error {
	_, err := q.db.Exec(ctx, createOrg, arg.ID, arg.Name)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, org_id, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	OrgID     uuid.UUID
	ExpiresAt time.Time
	Ip        string
	UserAgent string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.OrgID,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const createToken = `-- name: CreateToken :exec
INSERT INTO api_tokens (id, org_id, user_id, name, prefix, token_hash, role, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateTokenParams struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	UserID    uuid.UUID
	Name      string
	Prefix    string
	TokenHash []byte
	Role      string
	ExpiresAt *time.Time
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.Exec(ctx, createToken,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.TokenHash,
		arg.Role,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, name, password_hash) VALUES ($1, $2, $3, $4)
`

type CreateUserParams struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteToken = `-- name: DeleteToken :execrows
DELETE FROM api_tokens WHERE id = $1 AND user_id = $2
`

type DeleteTokenParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteToken(ctx context.Context, arg DeleteTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getMember = `-- name: GetMember :one
SELECT u.id, u.email, u.name, u.created_at, u.last_login_at, m.role
FROM memberships m JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1 AND u.id = $2
`

type GetMemberParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

type GetMemberRow struct {
	ID          uuid.UUID
	Email       string
	Name        string
	CreatedAt   time.Time
	LastLoginAt *time.Time
	Role        string
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (GetMemberRow, error) {
	row := q.db.QueryRow(ctx, getMember, arg.OrgID, arg.ID)
	var i GetMemberRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.Role,
	)
	return i, err
}

const getMembershipForUser = `-- name: GetMembershipForUser :one
SELECT m.org_id, m.role, o.name AS org_name
FROM memberships m JOIN orgs o ON o.id = m.org_id
WHERE m.user_id = $1
ORDER BY m.created_at
LIMIT 1
`

type GetMembershipForUserRow struct {
	OrgID   uuid.UUID
	Role    string
	OrgName string
}

func (q *Queries) GetMembershipForUser(ctx context.Context, userID uuid.UUID) (GetMembershipForUserRow, error) {
	row := q.db.QueryRow(ctx, getMembershipForUser, userID)
	var i GetMembershipForUserRow
	err := row.Scan(&i.OrgID, &i.Role, &i.OrgName)
	return i, err
}

const getOrg = `-- name: GetOrg :one
SELECT id, name, created_at FROM orgs WHERE id = $1
`

func (q *Queries) GetOrg(ctx context.Context, id uuid.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, getOrg, id)
	var i Org
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT s.user_id, s.org_id, s.expires_at, u.email, u.name, m.role, o.name AS org_name
FROM sessions s
JOIN users u ON u.id = s.user_id
JOIN memberships m ON m.user_id = s.user_id AND m.org_id = s.org_id
JOIN orgs o ON o.id = s.org_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionRow struct {
	UserID    uuid.UUID
	OrgID     uuid.UUID
	ExpiresAt time.Time
	Email     string
	Name      string
	Role      string
	OrgName   string
}

func (q *Queries) GetSession(ctx context.Context, tokenHash []byte) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i GetSessionRow
	err := row.Scan(
		&i.UserID,
		&i.OrgID,
		&i.ExpiresAt,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.OrgName,
	)
	return i, err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT t.id, t.user_id, t.org_id, t.name, t.role AS token_role, t.expires_at,
       u.email, u.name AS user_name, m.role AS user_role, o.name AS org_name
FROM api_tokens t
JOIN users u ON u.id = t.user_id
JOIN memberships m ON m.user_id = t.user_id AND m.org_id = t.org_id
JOIN orgs o ON o.id = t.org_id
WHERE t.token_hash = $1 AND (t.expires_at IS NULL OR t.expires_at > now())
`

type GetTokenByHashRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	OrgID     uuid.UUID
	Name      string
	TokenRole string
	ExpiresAt *time.Time
	Email     string
	UserName  string
	UserRole  string
	OrgName   string
}

func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash []byte) (GetTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getTokenByHash, tokenHash)
	var i GetTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.TokenRole,
		&i.ExpiresAt,
		&i.Email,
		&i.UserName,
		&i.UserRole,
		&i.OrgName,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, password_hash, created_at, last_login_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, created_at, last_login_at FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (org_id, actor, actor_id, action, subject, details, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditParams struct {
	OrgID   uuid.UUID
	Actor   string
	ActorID *uuid.UUID
	Action  string
	Subject string
	Details json.RawMessage
	Ip      string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.OrgID,
		arg.Actor,
		arg.ActorID,
		arg.Action,
		arg.Subject,
		arg.Details,
		arg.Ip,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT id, org_id, at, actor, actor_id, action, subject, details, ip FROM audit_log
WHERE org_id = $1 AND at < $3
ORDER BY at DESC
LIMIT $2
`

type ListAuditParams struct {
	OrgID  uuid.UUID
	Limit  int32
	Before time.Time
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAudit, arg.OrgID, arg.Limit, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.At,
			&i.Actor,
			&i.ActorID,
			&i.Action,
			&i.Subject,
			&i.Details,
			&i.Ip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT u.id, u.email, u.name, u.created_at, u.last_login_at, m.role
FROM memberships m JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1
ORDER BY u.created_at
`

type ListMembersRow struct {
	ID          uuid.UUID
	Email       string
	Name        string
	CreatedAt   time.Time
	LastLoginAt *time.Time
	Role        string
}

func (q *Queries) ListMembers(ctx context.Context, orgID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokens = `-- name: ListTokens :many
SELECT id, org_id, user_id, name, prefix, token_hash, role, created_at, last_used_at, expires_at FROM api_tokens WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTokens(ctx context.Context, userID uuid.UUID) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.TokenHash,
			&i.Role,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchToken = `-- name: TouchToken :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchToken, id)
	return err
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) TouchUserLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLogin, id)
	return err
}

const updateMembershipRole = `-- name: UpdateMembershipRole :exec
UPDATE memberships SET role = $3 WHERE org_id = $1 AND user_id = $2
`

type UpdateMembershipRoleParams struct {
	OrgID  uuid.UUID
	UserID uuid.UUID
	Role   string
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error {
	_, err := q.db.Exec(ctx, updateMembershipRole, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE users SET name = $2 WHERE id = $1
`

type UpdateUserNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, updateUserName, arg.ID, arg.Name)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
