// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: integrations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createIntegration = `-- name: CreateIntegration :exec
INSERT INTO integrations (id, org_id, name, kind, url, ciphertext, wrapped_key, key_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateIntegrationParams struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	Name       string
	Kind       string
	Url        string
	Ciphertext []byte
	WrappedKey []byte
	KeyID      *string
	CreatedBy  *uuid.UUID
}

func (q *Queries) CreateIntegration(ctx context.Context, arg CreateIntegrationParams) error {
	_, err := q.db.Exec(ctx, createIntegration,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Kind,
		arg.Url,
		arg.Ciphertext,
		arg.WrappedKey,
		arg.KeyID,
		arg.CreatedBy,
	)
	return err
}

const createNotificationChannel = `-- name: CreateNotificationChannel :exec
INSERT INTO notification_channels (id, org_id, name, kind, events, allow_private, url_hint,
    url_ciphertext, url_wrapped_key, secret_ciphertext, secret_wrapped_key, key_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateNotificationChannelParams struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	Name             string
	Kind             string
	Events           []string
	AllowPrivate     bool
	UrlHint          string
	UrlCiphertext    []byte
	UrlWrappedKey    []byte
	SecretCiphertext []byte
	SecretWrappedKey []byte
	KeyID            string
	CreatedBy        *uuid.UUID
}

func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) error {
	_, err := q.db.Exec(ctx, createNotificationChannel,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Kind,
		arg.Events,
		arg.AllowPrivate,
		arg.UrlHint,
		arg.UrlCiphertext,
		arg.UrlWrappedKey,
		arg.SecretCiphertext,
		arg.SecretWrappedKey,
		arg.KeyID,
		arg.CreatedBy,
	)
	return err
}

const deleteIntegration = `-- name: DeleteIntegration :execrows
DELETE FROM integrations WHERE id = $1 AND org_id = $2
`

type DeleteIntegrationParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteIntegration(ctx context.Context, arg DeleteIntegrationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIntegration, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :execrows
DELETE FROM notification_channels WHERE id = $1 AND org_id = $2
`

type DeleteNotificationChannelParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteNotificationChannel(ctx context.Context, arg DeleteNotificationChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationChannel, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIntegration = `-- name: GetIntegration :one
SELECT id, org_id, name, kind, url, ciphertext, wrapped_key, key_id, created_by, created_at, updated_at FROM integrations WHERE id = $1 AND org_id = $2
`

type GetIntegrationParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetIntegration(ctx context.Context, arg GetIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegration, arg.ID, arg.OrgID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Url,
		&i.Ciphertext,
		&i.WrappedKey,
		&i.KeyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationByName = `-- name: GetIntegrationByName :one
SELECT id, org_id, name, kind, url, ciphertext, wrapped_key, key_id, created_by, created_at, updated_at FROM integrations WHERE org_id = $1 AND name = $2
`

type GetIntegrationByNameParams struct {
	OrgID uuid.UUID
	Name  string
}

func (q *Queries) GetIntegrationByName(ctx context.Context, arg GetIntegrationByNameParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByName, arg.OrgID, arg.Name)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Url,
		&i.Ciphertext,
		&i.WrappedKey,
		&i.KeyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, org_id, name, kind, events, allow_private, url_hint, url_ciphertext, url_wrapped_key, secret_ciphertext, secret_wrapped_key, key_id, created_by, created_at FROM notification_channels WHERE id = $1 AND org_id = $2
`

type GetNotificationChannelParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetNotificationChannel(ctx context.Context, arg GetNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannel, arg.ID, arg.OrgID)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Events,
		&i.AllowPrivate,
		&i.UrlHint,
		&i.UrlCiphertext,
		&i.UrlWrappedKey,
		&i.SecretCiphertext,
		&i.SecretWrappedKey,
		&i.KeyID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertNotificationDelivery = `-- name: InsertNotificationDelivery :exec
INSERT INTO notification_deliveries (channel_id, delivery_id, event, run_id, attempt, ok, status_code, error, duration_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertNotificationDeliveryParams struct {
	ChannelID  uuid.UUID
	DeliveryID uuid.UUID
	Event      string
	RunID      *uuid.UUID
	Attempt    int32
	Ok         bool
	StatusCode int32
	Error      string
	DurationMs int32
}

func (q *Queries) InsertNotificationDelivery(ctx context.Context, arg InsertNotificationDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertNotificationDelivery,
		arg.ChannelID,
		arg.DeliveryID,
		arg.Event,
		arg.RunID,
		arg.Attempt,
		arg.Ok,
		arg.StatusCode,
		arg.Error,
		arg.DurationMs,
	)
	return err
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT id, org_id, name, kind, url, ciphertext, wrapped_key, key_id, created_by, created_at, updated_at FROM integrations WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListIntegrations(ctx context.Context, orgID uuid.UUID) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrations, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Kind,
			&i.Url,
			&i.Ciphertext,
			&i.WrappedKey,
			&i.KeyID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, org_id, name, kind, events, allow_private, url_hint, url_ciphertext, url_wrapped_key, secret_ciphertext, secret_wrapped_key, key_id, created_by, created_at FROM notification_channels WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListNotificationChannels(ctx context.Context, orgID uuid.UUID) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannels, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Kind,
			&i.Events,
			&i.AllowPrivate,
			&i.UrlHint,
			&i.UrlCiphertext,
			&i.UrlWrappedKey,
			&i.SecretCiphertext,
			&i.SecretWrappedKey,
			&i.KeyID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannelsForEvent = `-- name: ListNotificationChannelsForEvent :many
SELECT id, org_id, name, kind, events, allow_private, url_hint, url_ciphertext, url_wrapped_key, secret_ciphertext, secret_wrapped_key, key_id, created_by, created_at FROM notification_channels WHERE org_id = $1 AND $2::text = ANY (events) ORDER BY name
`

type ListNotificationChannelsForEventParams struct {
	OrgID uuid.UUID
	Event string
}

func (q *Queries) ListNotificationChannelsForEvent(ctx context.Context, arg ListNotificationChannelsForEventParams) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannelsForEvent, arg.OrgID, arg.Event)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Kind,
			&i.Events,
			&i.AllowPrivate,
			&i.UrlHint,
			&i.UrlCiphertext,
			&i.UrlWrappedKey,
			&i.SecretCiphertext,
			&i.SecretWrappedKey,
			&i.KeyID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationDeliveries = `-- name: ListNotificationDeliveries :many
SELECT id, channel_id, delivery_id, event, run_id, attempt, ok, status_code, error, duration_ms, at FROM notification_deliveries WHERE channel_id = $1 ORDER BY id DESC LIMIT $2
`

type ListNotificationDeliveriesParams struct {
	ChannelID uuid.UUID
	Limit     int32
}

func (q *Queries) ListNotificationDeliveries(ctx context.Context, arg ListNotificationDeliveriesParams) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, listNotificationDeliveries, arg.ChannelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.DeliveryID,
			&i.Event,
			&i.RunID,
			&i.Attempt,
			&i.Ok,
			&i.StatusCode,
			&i.Error,
			&i.DurationMs,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneNotificationDeliveries = `-- name: PruneNotificationDeliveries :exec
DELETE FROM notification_deliveries AS old
WHERE old.channel_id = $1::uuid
  AND old.id < (
    SELECT COALESCE(MIN(newest.id), 0) FROM (
      SELECT d.id FROM notification_deliveries AS d
      WHERE d.channel_id = $1::uuid
      ORDER BY d.id DESC LIMIT $2::int
    ) AS newest
  )
`

type PruneNotificationDeliveriesParams struct {
	ChannelID uuid.UUID
	Keep      int32
}

func (q *Queries) PruneNotificationDeliveries(ctx context.Context, arg PruneNotificationDeliveriesParams) error {
	_, err := q.db.Exec(ctx, pruneNotificationDeliveries, arg.ChannelID, arg.Keep)
	return err
}
