// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, org_id, name, slug, description) VALUES ($1, $2, $3, $4, $5)
`

type CreateProjectParams struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	Name        string
	Slug        string
	Description string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.Exec(ctx, createProject,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	return err
}

const createTarget = `-- name: CreateTarget :exec
INSERT INTO targets (id, project_id, name, base_url, host, private, verification_token, allow_hosts, max_rate, max_vus, max_duration_s)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateTargetParams struct {
	ID                uuid.UUID
	ProjectID         uuid.UUID
	Name              string
	BaseUrl           string
	Host              string
	Private           bool
	VerificationToken string
	AllowHosts        []string
	MaxRate           *float64
	MaxVus            *int32
	MaxDurationS      *int32
}

func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) error {
	_, err := q.db.Exec(ctx, createTarget,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.BaseUrl,
		arg.Host,
		arg.Private,
		arg.VerificationToken,
		arg.AllowHosts,
		arg.MaxRate,
		arg.MaxVus,
		arg.MaxDurationS,
	)
	return err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = $1 AND org_id = $2
`

type DeleteProjectParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSecret = `-- name: DeleteSecret :execrows
DELETE FROM secrets WHERE project_id = $1 AND name = $2
`

type DeleteSecretParams struct {
	ProjectID uuid.UUID
	Name      string
}

func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSecret, arg.ProjectID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTarget = `-- name: DeleteTarget :execrows
DELETE FROM targets t USING projects p
WHERE t.id = $1 AND p.id = t.project_id AND p.org_id = $2
`

type DeleteTargetParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteTarget(ctx context.Context, arg DeleteTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTarget, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProject = `-- name: GetProject :one
SELECT id, org_id, name, slug, description, created_at FROM projects WHERE id = $1 AND org_id = $2
`

type GetProjectParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.OrgID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getTarget = `-- name: GetTarget :one
SELECT t.id, t.project_id, t.name, t.base_url, t.host, t.private, t.verification_token, t.verified_at, t.verification_method, t.allow_hosts, t.max_rate, t.max_vus, t.max_duration_s, t.created_at FROM targets t JOIN projects p ON p.id = t.project_id
WHERE t.id = $1 AND p.org_id = $2
`

type GetTargetParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetTarget(ctx context.Context, arg GetTargetParams) (Target, error) {
	row := q.db.QueryRow(ctx, getTarget, arg.ID, arg.OrgID)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.BaseUrl,
		&i.Host,
		&i.Private,
		&i.VerificationToken,
		&i.VerifiedAt,
		&i.VerificationMethod,
		&i.AllowHosts,
		&i.MaxRate,
		&i.MaxVus,
		&i.MaxDurationS,
		&i.CreatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, org_id, name, slug, description, created_at FROM projects WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context, orgID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretNames = `-- name: ListSecretNames :many
SELECT name, updated_at FROM secrets WHERE project_id = $1 ORDER BY name
`

type ListSecretNamesRow struct {
	Name      string
	UpdatedAt time.Time
}

func (q *Queries) ListSecretNames(ctx context.Context, projectID uuid.UUID) ([]ListSecretNamesRow, error) {
	rows, err := q.db.Query(ctx, listSecretNames, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretNamesRow{}
	for rows.Next() {
		var i ListSecretNamesRow
		if err := rows.Scan(&i.Name, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecrets = `-- name: ListSecrets :many
SELECT project_id, name, ciphertext, wrapped_key, key_id, updated_at FROM secrets WHERE project_id = $1
`

func (q *Queries) ListSecrets(ctx context.Context, projectID uuid.UUID) ([]Secret, error) {
	rows, err := q.db.Query(ctx, listSecrets, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Secret{}
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ProjectID,
			&i.Name,
			&i.Ciphertext,
			&i.WrappedKey,
			&i.KeyID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargets = `-- name: ListTargets :many
SELECT id, project_id, name, base_url, host, private, verification_token, verified_at, verification_method, allow_hosts, max_rate, max_vus, max_duration_s, created_at FROM targets WHERE project_id = $1 ORDER BY name
`

func (q *Queries) ListTargets(ctx context.Context, projectID uuid.UUID) ([]Target, error) {
	rows, err := q.db.Query(ctx, listTargets, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Target{}
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.BaseUrl,
			&i.Host,
			&i.Private,
			&i.VerificationToken,
			&i.VerifiedAt,
			&i.VerificationMethod,
			&i.AllowHosts,
			&i.MaxRate,
			&i.MaxVus,
			&i.MaxDurationS,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSecret = `-- name: PutSecret :one
INSERT INTO secrets (project_id, name, ciphertext, wrapped_key, key_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, name) DO UPDATE
SET ciphertext = EXCLUDED.ciphertext, wrapped_key = EXCLUDED.wrapped_key, key_id = EXCLUDED.key_id, updated_at = now()
RETURNING updated_at
`

type PutSecretParams struct {
	ProjectID  uuid.UUID
	Name       string
	Ciphertext []byte
	WrappedKey []byte
	KeyID      string
}

func (q *Queries) PutSecret(ctx context.Context, arg PutSecretParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, putSecret,
		arg.ProjectID,
		arg.Name,
		arg.Ciphertext,
		arg.WrappedKey,
		arg.KeyID,
	)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}

const setTargetVerified = `-- name: SetTargetVerified :exec
UPDATE targets SET verified_at = now(), verification_method = $2 WHERE id = $1
`

type SetTargetVerifiedParams struct {
	ID                 uuid.UUID
	VerificationMethod *string
}

func (q *Queries) SetTargetVerified(ctx context.Context, arg SetTargetVerifiedParams) error {
	_, err := q.db.Exec(ctx, setTargetVerified, arg.ID, arg.VerificationMethod)
	return err
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects SET name = $3, slug = $4, description = $5 WHERE id = $1 AND org_id = $2
`

type UpdateProjectParams struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	Name        string
	Slug        string
	Description string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.Exec(ctx, updateProject,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	return err
}

const updateTarget = `-- name: UpdateTarget :exec
UPDATE targets SET name = $2, base_url = $3, host = $4, private = $5, allow_hosts = $6,
    max_rate = $7, max_vus = $8, max_duration_s = $9,
    verified_at = CASE WHEN host = $4 THEN verified_at END,
    verification_method = CASE WHEN host = $4 THEN verification_method END
WHERE id = $1
`

type UpdateTargetParams struct {
	ID           uuid.UUID
	Name         string
	BaseUrl      string
	Host         string
	Private      bool
	AllowHosts   []string
	MaxRate      *float64
	MaxVus       *int32
	MaxDurationS *int32
}

func (q *Queries) UpdateTarget(ctx context.Context, arg UpdateTargetParams) error {
	_, err := q.db.Exec(ctx, updateTarget,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.Host,
		arg.Private,
		arg.AllowHosts,
		arg.MaxRate,
		arg.MaxVus,
		arg.MaxDurationS,
	)
	return err
}
