// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: replicas.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteReplica = `-- name: DeleteReplica :exec
DELETE FROM replicas WHERE id = $1
`

func (q *Queries) DeleteReplica(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReplica, id)
	return err
}

const deleteStaleReplicas = `-- name: DeleteStaleReplicas :exec
DELETE FROM replicas WHERE last_seen < $1
`

func (q *Queries) DeleteStaleReplicas(ctx context.Context, lastSeen time.Time) error {
	_, err := q.db.Exec(ctx, deleteStaleReplicas, lastSeen)
	return err
}

const failOrphanedAIJobs = `-- name: FailOrphanedAIJobs :execrows
UPDATE ai_jobs j
SET status = 'failed', error = 'interrupted: the server stopped before the job finished', finished_at = now()
WHERE j.status IN ('queued', 'running')
  AND (j.owner_replica IS NULL OR NOT EXISTS (
        SELECT 1 FROM replicas p WHERE p.id = j.owner_replica AND p.last_seen >= $1))
`

func (q *Queries) FailOrphanedAIJobs(ctx context.Context, lastSeen time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, failOrphanedAIJobs, lastSeen)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRunOwner = `-- name: GetRunOwner :one
SELECT owner_replica FROM runs WHERE id = $1
`

func (q *Queries) GetRunOwner(ctx context.Context, id uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getRunOwner, id)
	var owner_replica *uuid.UUID
	err := row.Scan(&owner_replica)
	return owner_replica, err
}

const listOrphanedRuns = `-- name: ListOrphanedRuns :many
SELECT r.id FROM runs r
WHERE r.status IN ('scheduling', 'starting', 'running', 'stopping', 'analyzing')
  AND (r.owner_replica IS NULL OR NOT EXISTS (
        SELECT 1 FROM replicas p WHERE p.id = r.owner_replica AND p.last_seen >= $1))
`

// Unfinished runs whose owner has no fresh heartbeat (or no owner at all).
func (q *Queries) ListOrphanedRuns(ctx context.Context, lastSeen time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listOrphanedRuns, lastSeen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplicas = `-- name: ListReplicas :many
SELECT id, addr, version, started_at, last_seen FROM replicas ORDER BY started_at
`

func (q *Queries) ListReplicas(ctx context.Context) ([]Replica, error) {
	rows, err := q.db.Query(ctx, listReplicas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Replica{}
	for rows.Next() {
		var i Replica
		if err := rows.Scan(
			&i.ID,
			&i.Addr,
			&i.Version,
			&i.StartedAt,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAIJobOwner = `-- name: SetAIJobOwner :exec
UPDATE ai_jobs SET owner_replica = $2 WHERE id = $1
`

type SetAIJobOwnerParams struct {
	ID           uuid.UUID
	OwnerReplica *uuid.UUID
}

func (q *Queries) SetAIJobOwner(ctx context.Context, arg SetAIJobOwnerParams) error {
	_, err := q.db.Exec(ctx, setAIJobOwner, arg.ID, arg.OwnerReplica)
	return err
}

const setRunOwner = `-- name: SetRunOwner :exec
UPDATE runs SET owner_replica = $2 WHERE id = $1
`

type SetRunOwnerParams struct {
	ID           uuid.UUID
	OwnerReplica *uuid.UUID
}

func (q *Queries) SetRunOwner(ctx context.Context, arg SetRunOwnerParams) error {
	_, err := q.db.Exec(ctx, setRunOwner, arg.ID, arg.OwnerReplica)
	return err
}

const touchReplica = `-- name: TouchReplica :exec
UPDATE replicas SET last_seen = now() WHERE id = $1
`

func (q *Queries) TouchReplica(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchReplica, id)
	return err
}

const upsertReplica = `-- name: UpsertReplica :exec
INSERT INTO replicas (id, addr, version) VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET last_seen = now(), addr = EXCLUDED.addr, version = EXCLUDED.version
`

type UpsertReplicaParams struct {
	ID      uuid.UUID
	Addr    string
	Version string
}

func (q *Queries) UpsertReplica(ctx context.Context, arg UpsertReplicaParams) error {
	_, err := q.db.Exec(ctx, upsertReplica, arg.ID, arg.Addr, arg.Version)
	return err
}
