// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: runs.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createRun = `-- name: CreateRun :exec
INSERT INTO runs (id, project_id, scenario_id, scenario_version, target_id, status, overrides, plan, env, workers, note, created_by)
VALUES ($1, $2, $3, $4, $5, 'scheduling', $6, $7, $8, $9, $10, $11)
`

type CreateRunParams struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	ScenarioID      uuid.UUID
	ScenarioVersion int32
	TargetID        uuid.UUID
	Overrides       json.RawMessage
	Plan            json.RawMessage
	Env             json.RawMessage
	Workers         int32
	Note            string
	CreatedBy       *uuid.UUID
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.Exec(ctx, createRun,
		arg.ID,
		arg.ProjectID,
		arg.ScenarioID,
		arg.ScenarioVersion,
		arg.TargetID,
		arg.Overrides,
		arg.Plan,
		arg.Env,
		arg.Workers,
		arg.Note,
		arg.CreatedBy,
	)
	return err
}

const finishRun = `-- name: FinishRun :exec
UPDATE runs SET status = $2, verdict = $3, stop_reason = $4, error = $5, summary = $6, ended_at = now()
WHERE id = $1
`

type FinishRunParams struct {
	ID         uuid.UUID
	Status     string
	Verdict    *string
	StopReason *string
	Error      *string
	Summary    json.RawMessage
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.Exec(ctx, finishRun,
		arg.ID,
		arg.Status,
		arg.Verdict,
		arg.StopReason,
		arg.Error,
		arg.Summary,
	)
	return err
}

const getReport = `-- name: GetReport :one
SELECT report FROM reports WHERE run_id = $1
`

func (q *Queries) GetReport(ctx context.Context, runID uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getReport, runID)
	var report json.RawMessage
	err := row.Scan(&report)
	return report, err
}

const getRun = `-- name: GetRun :one
SELECT r.id, r.project_id, r.scenario_id, r.scenario_version, r.target_id, r.status, r.verdict, r.stop_reason, r.error, r.overrides, r.plan, r.env, r.workers, r.note, r.summary, r.created_by, r.created_at, r.started_at, r.ended_at, r.owner_replica, s.name AS scenario_name, t.base_url AS target_url
FROM runs r
JOIN projects p ON p.id = r.project_id
JOIN scenarios s ON s.id = r.scenario_id
JOIN targets t ON t.id = r.target_id
WHERE r.id = $1 AND p.org_id = $2
`

type GetRunParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

type GetRunRow struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	ScenarioID      uuid.UUID
	ScenarioVersion int32
	TargetID        uuid.UUID
	Status          string
	Verdict         *string
	StopReason      *string
	Error           *string
	Overrides       json.RawMessage
	Plan            json.RawMessage
	Env             json.RawMessage
	Workers         int32
	Note            string
	Summary         json.RawMessage
	CreatedBy       *uuid.UUID
	CreatedAt       time.Time
	StartedAt       *time.Time
	EndedAt         *time.Time
	OwnerReplica    *uuid.UUID
	ScenarioName    string
	TargetUrl       string
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (GetRunRow, error) {
	row := q.db.QueryRow(ctx, getRun, arg.ID, arg.OrgID)
	var i GetRunRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ScenarioID,
		&i.ScenarioVersion,
		&i.TargetID,
		&i.Status,
		&i.Verdict,
		&i.StopReason,
		&i.Error,
		&i.Overrides,
		&i.Plan,
		&i.Env,
		&i.Workers,
		&i.Note,
		&i.Summary,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.OwnerReplica,
		&i.ScenarioName,
		&i.TargetUrl,
	)
	return i, err
}

const insertRunEvent = `-- name: InsertRunEvent :exec
INSERT INTO run_events (run_id, type, message, worker, details) VALUES ($1, $2, $3, $4, $5)
`

type InsertRunEventParams struct {
	RunID   uuid.UUID
	Type    string
	Message string
	Worker  string
	Details json.RawMessage
}

func (q *Queries) InsertRunEvent(ctx context.Context, arg InsertRunEventParams) error {
	_, err := q.db.Exec(ctx, insertRunEvent,
		arg.RunID,
		arg.Type,
		arg.Message,
		arg.Worker,
		arg.Details,
	)
	return err
}

const insertRunMetric = `-- name: InsertRunMetric :exec
INSERT INTO run_metrics (run_id, ts, interval, requests, failed, rps, error_rate, p50, p95, p99, vus, planned, dropped, iterations, sched_lag, snapshot)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT DO NOTHING
`

type InsertRunMetricParams struct {
	RunID      uuid.UUID
	Ts         time.Time
	Interval   int32
	Requests   int64
	Failed     int64
	Rps        float64
	ErrorRate  float64
	P50        float64
	P95        float64
	P99        float64
	Vus        int32
	Planned    float64
	Dropped    int64
	Iterations int64
	SchedLag   float64
	Snapshot   []byte
}

func (q *Queries) InsertRunMetric(ctx context.Context, arg InsertRunMetricParams) error {
	_, err := q.db.Exec(ctx, insertRunMetric,
		arg.RunID,
		arg.Ts,
		arg.Interval,
		arg.Requests,
		arg.Failed,
		arg.Rps,
		arg.ErrorRate,
		arg.P50,
		arg.P95,
		arg.P99,
		arg.Vus,
		arg.Planned,
		arg.Dropped,
		arg.Iterations,
		arg.SchedLag,
		arg.Snapshot,
	)
	return err
}

const listActiveRuns = `-- name: ListActiveRuns :many
SELECT r.id FROM runs r JOIN projects p ON p.id = r.project_id
WHERE p.org_id = $1 AND r.status IN ('scheduling', 'starting', 'running', 'stopping')
`

func (q *Queries) ListActiveRuns(ctx context.Context, orgID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveRuns, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunEvents = `-- name: ListRunEvents :many
SELECT id, run_id, at, type, message, worker, details FROM run_events WHERE run_id = $1 ORDER BY id
`

func (q *Queries) ListRunEvents(ctx context.Context, runID uuid.UUID) ([]RunEvent, error) {
	rows, err := q.db.Query(ctx, listRunEvents, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunEvent{}
	for rows.Next() {
		var i RunEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.At,
			&i.Type,
			&i.Message,
			&i.Worker,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunPoints = `-- name: ListRunPoints :many
SELECT interval, requests, failed, rps, error_rate, p50, p95, p99, vus, planned, dropped, iterations, sched_lag
FROM run_metrics WHERE run_id = $1 ORDER BY interval
`

type ListRunPointsRow struct {
	Interval   int32
	Requests   int64
	Failed     int64
	Rps        float64
	ErrorRate  float64
	P50        float64
	P95        float64
	P99        float64
	Vus        int32
	Planned    float64
	Dropped    int64
	Iterations int64
	SchedLag   float64
}

func (q *Queries) ListRunPoints(ctx context.Context, runID uuid.UUID) ([]ListRunPointsRow, error) {
	rows, err := q.db.Query(ctx, listRunPoints, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunPointsRow{}
	for rows.Next() {
		var i ListRunPointsRow
		if err := rows.Scan(
			&i.Interval,
			&i.Requests,
			&i.Failed,
			&i.Rps,
			&i.ErrorRate,
			&i.P50,
			&i.P95,
			&i.P99,
			&i.Vus,
			&i.Planned,
			&i.Dropped,
			&i.Iterations,
			&i.SchedLag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunSnapshots = `-- name: ListRunSnapshots :many
SELECT snapshot FROM run_metrics WHERE run_id = $1 ORDER BY interval
`

func (q *Queries) ListRunSnapshots(ctx context.Context, runID uuid.UUID) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listRunSnapshots, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var snapshot []byte
		if err := rows.Scan(&snapshot); err != nil {
			return nil, err
		}
		items = append(items, snapshot)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT r.id, r.project_id, r.scenario_id, r.scenario_version, r.target_id, r.status, r.verdict, r.stop_reason, r.error, r.overrides, r.plan, r.env, r.workers, r.note, r.summary, r.created_by, r.created_at, r.started_at, r.ended_at, r.owner_replica, s.name AS scenario_name, t.base_url AS target_url
FROM runs r
JOIN scenarios s ON s.id = r.scenario_id
JOIN targets t ON t.id = r.target_id
WHERE r.project_id = $1
  AND ($3::uuid IS NULL OR r.scenario_id = $3)
  AND r.created_at < $4
ORDER BY r.created_at DESC
LIMIT $2
`

type ListRunsParams struct {
	ProjectID  uuid.UUID
	Limit      int32
	ScenarioID *uuid.UUID
	Before     time.Time
}

type ListRunsRow struct {
	ID              uuid.UUID
	ProjectID       uuid.UUID
	ScenarioID      uuid.UUID
	ScenarioVersion int32
	TargetID        uuid.UUID
	Status          string
	Verdict         *string
	StopReason      *string
	Error           *string
	Overrides       json.RawMessage
	Plan            json.RawMessage
	Env             json.RawMessage
	Workers         int32
	Note            string
	Summary         json.RawMessage
	CreatedBy       *uuid.UUID
	CreatedAt       time.Time
	StartedAt       *time.Time
	EndedAt         *time.Time
	OwnerReplica    *uuid.UUID
	ScenarioName    string
	TargetUrl       string
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]ListRunsRow, error) {
	rows, err := q.db.Query(ctx, listRuns,
		arg.ProjectID,
		arg.Limit,
		arg.ScenarioID,
		arg.Before,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsRow{}
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ScenarioID,
			&i.ScenarioVersion,
			&i.TargetID,
			&i.Status,
			&i.Verdict,
			&i.StopReason,
			&i.Error,
			&i.Overrides,
			&i.Plan,
			&i.Env,
			&i.Workers,
			&i.Note,
			&i.Summary,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.OwnerReplica,
			&i.ScenarioName,
			&i.TargetUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnfinishedRuns = `-- name: ListUnfinishedRuns :many
SELECT id FROM runs WHERE status IN ('scheduling', 'starting', 'running', 'stopping', 'analyzing')
`

func (q *Queries) ListUnfinishedRuns(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUnfinishedRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunStarted = `-- name: MarkRunStarted :exec
UPDATE runs SET status = 'running', started_at = $2 WHERE id = $1
`

type MarkRunStartedParams struct {
	ID        uuid.UUID
	StartedAt *time.Time
}

func (q *Queries) MarkRunStarted(ctx context.Context, arg MarkRunStartedParams) error {
	_, err := q.db.Exec(ctx, markRunStarted, arg.ID, arg.StartedAt)
	return err
}

const saveReport = `-- name: SaveReport :exec
INSERT INTO reports (run_id, report) VALUES ($1, $2)
ON CONFLICT (run_id) DO UPDATE SET report = EXCLUDED.report, created_at = now()
`

type SaveReportParams struct {
	RunID  uuid.UUID
	Report json.RawMessage
}

func (q *Queries) SaveReport(ctx context.Context, arg SaveReportParams) error {
	_, err := q.db.Exec(ctx, saveReport, arg.RunID, arg.Report)
	return err
}

const setRunStatus = `-- name: SetRunStatus :exec
UPDATE runs SET status = $2 WHERE id = $1
`

type SetRunStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetRunStatus(ctx context.Context, arg SetRunStatusParams) error {
	_, err := q.db.Exec(ctx, setRunStatus, arg.ID, arg.Status)
	return err
}

const setRunWorkers = `-- name: SetRunWorkers :exec
UPDATE runs SET workers = $2 WHERE id = $1
`

type SetRunWorkersParams struct {
	ID      uuid.UUID
	Workers int32
}

func (q *Queries) SetRunWorkers(ctx context.Context, arg SetRunWorkersParams) error {
	_, err := q.db.Exec(ctx, setRunWorkers, arg.ID, arg.Workers)
	return err
}
