// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scenarios.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createScenario = `-- name: CreateScenario :exec
INSERT INTO scenarios (id, project_id, name, description, tags) VALUES ($1, $2, $3, $4, $5)
`

type CreateScenarioParams struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Name        string
	Description string
	Tags        []string
}

func (q *Queries) CreateScenario(ctx context.Context, arg CreateScenarioParams) error {
	_, err := q.db.Exec(ctx, createScenario,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Tags,
	)
	return err
}

const createScenarioVersion = `-- name: CreateScenarioVersion :exec
INSERT INTO scenario_versions (scenario_id, version, yaml, message, plan, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateScenarioVersionParams struct {
	ScenarioID uuid.UUID
	Version    int32
	Yaml       string
	Message    string
	Plan       json.RawMessage
	CreatedBy  *uuid.UUID
}

func (q *Queries) CreateScenarioVersion(ctx context.Context, arg CreateScenarioVersionParams) error {
	_, err := q.db.Exec(ctx, createScenarioVersion,
		arg.ScenarioID,
		arg.Version,
		arg.Yaml,
		arg.Message,
		arg.Plan,
		arg.CreatedBy,
	)
	return err
}

const deleteScenario = `-- name: DeleteScenario :execrows
DELETE FROM scenarios s USING projects p
WHERE s.id = $1 AND p.id = s.project_id AND p.org_id = $2
`

type DeleteScenarioParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteScenario(ctx context.Context, arg DeleteScenarioParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScenario, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestScenarioVersion = `-- name: GetLatestScenarioVersion :one
SELECT scenario_id, version, yaml, message, plan, created_by, created_at FROM scenario_versions WHERE scenario_id = $1 ORDER BY version DESC LIMIT 1
`

func (q *Queries) GetLatestScenarioVersion(ctx context.Context, scenarioID uuid.UUID) (ScenarioVersion, error) {
	row := q.db.QueryRow(ctx, getLatestScenarioVersion, scenarioID)
	var i ScenarioVersion
	err := row.Scan(
		&i.ScenarioID,
		&i.Version,
		&i.Yaml,
		&i.Message,
		&i.Plan,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getScenario = `-- name: GetScenario :one
SELECT s.id, s.project_id, s.name, s.description, s.tags, s.created_at, s.updated_at FROM scenarios s JOIN projects p ON p.id = s.project_id
WHERE s.id = $1 AND p.org_id = $2
`

type GetScenarioParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetScenario(ctx context.Context, arg GetScenarioParams) (Scenario, error) {
	row := q.db.QueryRow(ctx, getScenario, arg.ID, arg.OrgID)
	var i Scenario
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScenarioVersion = `-- name: GetScenarioVersion :one
SELECT scenario_id, version, yaml, message, plan, created_by, created_at FROM scenario_versions WHERE scenario_id = $1 AND version = $2
`

type GetScenarioVersionParams struct {
	ScenarioID uuid.UUID
	Version    int32
}

func (q *Queries) GetScenarioVersion(ctx context.Context, arg GetScenarioVersionParams) (ScenarioVersion, error) {
	row := q.db.QueryRow(ctx, getScenarioVersion, arg.ScenarioID, arg.Version)
	var i ScenarioVersion
	err := row.Scan(
		&i.ScenarioID,
		&i.Version,
		&i.Yaml,
		&i.Message,
		&i.Plan,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listScenarioVersions = `-- name: ListScenarioVersions :many
SELECT scenario_id, version, yaml, message, plan, created_by, created_at FROM scenario_versions WHERE scenario_id = $1 ORDER BY version DESC
`

func (q *Queries) ListScenarioVersions(ctx context.Context, scenarioID uuid.UUID) ([]ScenarioVersion, error) {
	rows, err := q.db.Query(ctx, listScenarioVersions, scenarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScenarioVersion{}
	for rows.Next() {
		var i ScenarioVersion
		if err := rows.Scan(
			&i.ScenarioID,
			&i.Version,
			&i.Yaml,
			&i.Message,
			&i.Plan,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenarios = `-- name: ListScenarios :many
SELECT id, project_id, name, description, tags, created_at, updated_at FROM scenarios WHERE project_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListScenarios(ctx context.Context, projectID uuid.UUID) ([]Scenario, error) {
	rows, err := q.db.Query(ctx, listScenarios, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scenario{}
	for rows.Next() {
		var i Scenario
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextScenarioVersion = `-- name: NextScenarioVersion :one
SELECT COALESCE(max(version), 0) + 1 AS next FROM scenario_versions WHERE scenario_id = $1
`

func (q *Queries) NextScenarioVersion(ctx context.Context, scenarioID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextScenarioVersion, scenarioID)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const updateScenarioMeta = `-- name: UpdateScenarioMeta :exec
UPDATE scenarios SET name = $2, description = $3, tags = $4, updated_at = now() WHERE id = $1
`

type UpdateScenarioMetaParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	Tags        []string
}

func (q *Queries) UpdateScenarioMeta(ctx context.Context, arg UpdateScenarioMetaParams) error {
	_, err := q.db.Exec(ctx, updateScenarioMeta,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Tags,
	)
	return err
}
