// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: schedules.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimSchedule = `-- name: ClaimSchedule :one
UPDATE schedules SET next_run_at = $1, last_fired_at = $2::timestamptz
WHERE id = $3 AND enabled AND next_run_at = $4::timestamptz AND next_run_at <= $2::timestamptz
RETURNING id
`

type ClaimScheduleParams struct {
	Next *time.Time
	Now  time.Time
	ID   uuid.UUID
	Due  time.Time
}

// Moves a due schedule to its next firing. Only one caller can match the
// old next_run_at, so concurrent claimers fire it once.
func (q *Queries) ClaimSchedule(ctx context.Context, arg ClaimScheduleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimSchedule,
		arg.Next,
		arg.Now,
		arg.ID,
		arg.Due,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createSchedule = `-- name: CreateSchedule :exec
INSERT INTO schedules (id, project_id, name, scenario_id, target_id, cron, timezone, overrides, env, workers, enabled, note, owner_id, next_run_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreateScheduleParams struct {
	ID         uuid.UUID
	ProjectID  uuid.UUID
	Name       string
	ScenarioID uuid.UUID
	TargetID   uuid.UUID
	Cron       string
	Timezone   string
	Overrides  json.RawMessage
	Env        json.RawMessage
	Workers    int32
	Enabled    bool
	Note       string
	OwnerID    *uuid.UUID
	NextRunAt  *time.Time
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) error {
	_, err := q.db.Exec(ctx, createSchedule,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.ScenarioID,
		arg.TargetID,
		arg.Cron,
		arg.Timezone,
		arg.Overrides,
		arg.Env,
		arg.Workers,
		arg.Enabled,
		arg.Note,
		arg.OwnerID,
		arg.NextRunAt,
	)
	return err
}

const deleteSchedule = `-- name: DeleteSchedule :execrows
DELETE FROM schedules WHERE id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSchedule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSchedule = `-- name: GetSchedule :one
SELECT sc.id, sc.project_id, sc.name, sc.scenario_id, sc.target_id, sc.cron, sc.timezone, sc.overrides, sc.env, sc.workers, sc.enabled, sc.note, sc.owner_id, sc.created_at, sc.updated_at, sc.next_run_at, sc.last_fired_at, sc.last_run_id, sc.last_skip_reason, p.org_id, s.name AS scenario_name, t.name AS target_name,
       u.email AS owner_email, r.status AS last_run_status, r.verdict AS last_run_verdict, r.created_at AS last_run_at
FROM schedules sc
JOIN projects p ON p.id = sc.project_id
JOIN scenarios s ON s.id = sc.scenario_id
JOIN targets t ON t.id = sc.target_id
LEFT JOIN users u ON u.id = sc.owner_id
LEFT JOIN runs r ON r.id = sc.last_run_id
WHERE sc.id = $1 AND p.org_id = $2
`

type GetScheduleParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

type GetScheduleRow struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Name           string
	ScenarioID     uuid.UUID
	TargetID       uuid.UUID
	Cron           string
	Timezone       string
	Overrides      json.RawMessage
	Env            json.RawMessage
	Workers        int32
	Enabled        bool
	Note           string
	OwnerID        *uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	NextRunAt      *time.Time
	LastFiredAt    *time.Time
	LastRunID      *uuid.UUID
	LastSkipReason string
	OrgID          uuid.UUID
	ScenarioName   string
	TargetName     string
	OwnerEmail     *string
	LastRunStatus  *string
	LastRunVerdict *string
	LastRunAt      *time.Time
}

func (q *Queries) GetSchedule(ctx context.Context, arg GetScheduleParams) (GetScheduleRow, error) {
	row := q.db.QueryRow(ctx, getSchedule, arg.ID, arg.OrgID)
	var i GetScheduleRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ScenarioID,
		&i.TargetID,
		&i.Cron,
		&i.Timezone,
		&i.Overrides,
		&i.Env,
		&i.Workers,
		&i.Enabled,
		&i.Note,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextRunAt,
		&i.LastFiredAt,
		&i.LastRunID,
		&i.LastSkipReason,
		&i.OrgID,
		&i.ScenarioName,
		&i.TargetName,
		&i.OwnerEmail,
		&i.LastRunStatus,
		&i.LastRunVerdict,
		&i.LastRunAt,
	)
	return i, err
}

const listDueSchedules = `-- name: ListDueSchedules :many
SELECT id, cron, timezone, next_run_at FROM schedules
WHERE enabled AND next_run_at <= $1::timestamptz
ORDER BY next_run_at
LIMIT 100
`

type ListDueSchedulesRow struct {
	ID        uuid.UUID
	Cron      string
	Timezone  string
	NextRunAt *time.Time
}

func (q *Queries) ListDueSchedules(ctx context.Context, now time.Time) ([]ListDueSchedulesRow, error) {
	rows, err := q.db.Query(ctx, listDueSchedules, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueSchedulesRow{}
	for rows.Next() {
		var i ListDueSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Cron,
			&i.Timezone,
			&i.NextRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT sc.id, sc.project_id, sc.name, sc.scenario_id, sc.target_id, sc.cron, sc.timezone, sc.overrides, sc.env, sc.workers, sc.enabled, sc.note, sc.owner_id, sc.created_at, sc.updated_at, sc.next_run_at, sc.last_fired_at, sc.last_run_id, sc.last_skip_reason, p.org_id, s.name AS scenario_name, t.name AS target_name,
       u.email AS owner_email, r.status AS last_run_status, r.verdict AS last_run_verdict, r.created_at AS last_run_at
FROM schedules sc
JOIN projects p ON p.id = sc.project_id
JOIN scenarios s ON s.id = sc.scenario_id
JOIN targets t ON t.id = sc.target_id
LEFT JOIN users u ON u.id = sc.owner_id
LEFT JOIN runs r ON r.id = sc.last_run_id
WHERE sc.project_id = $1
ORDER BY sc.name
`

type ListSchedulesRow struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Name           string
	ScenarioID     uuid.UUID
	TargetID       uuid.UUID
	Cron           string
	Timezone       string
	Overrides      json.RawMessage
	Env            json.RawMessage
	Workers        int32
	Enabled        bool
	Note           string
	OwnerID        *uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	NextRunAt      *time.Time
	LastFiredAt    *time.Time
	LastRunID      *uuid.UUID
	LastSkipReason string
	OrgID          uuid.UUID
	ScenarioName   string
	TargetName     string
	OwnerEmail     *string
	LastRunStatus  *string
	LastRunVerdict *string
	LastRunAt      *time.Time
}

func (q *Queries) ListSchedules(ctx context.Context, projectID uuid.UUID) ([]ListSchedulesRow, error) {
	rows, err := q.db.Query(ctx, listSchedules, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulesRow{}
	for rows.Next() {
		var i ListSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.ScenarioID,
			&i.TargetID,
			&i.Cron,
			&i.Timezone,
			&i.Overrides,
			&i.Env,
			&i.Workers,
			&i.Enabled,
			&i.Note,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextRunAt,
			&i.LastFiredAt,
			&i.LastRunID,
			&i.LastSkipReason,
			&i.OrgID,
			&i.ScenarioName,
			&i.TargetName,
			&i.OwnerEmail,
			&i.LastRunStatus,
			&i.LastRunVerdict,
			&i.LastRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordScheduleRun = `-- name: RecordScheduleRun :exec
UPDATE schedules SET last_run_id = $2, last_fired_at = $3, last_skip_reason = '' WHERE id = $1
`

type RecordScheduleRunParams struct {
	ID          uuid.UUID
	LastRunID   *uuid.UUID
	LastFiredAt *time.Time
}

func (q *Queries) RecordScheduleRun(ctx context.Context, arg RecordScheduleRunParams) error {
	_, err := q.db.Exec(ctx, recordScheduleRun, arg.ID, arg.LastRunID, arg.LastFiredAt)
	return err
}

const recordScheduleSkip = `-- name: RecordScheduleSkip :exec
UPDATE schedules SET last_skip_reason = $2 WHERE id = $1
`

type RecordScheduleSkipParams struct {
	ID             uuid.UUID
	LastSkipReason string
}

func (q *Queries) RecordScheduleSkip(ctx context.Context, arg RecordScheduleSkipParams) error {
	_, err := q.db.Exec(ctx, recordScheduleSkip, arg.ID, arg.LastSkipReason)
	return err
}

const updateSchedule = `-- name: UpdateSchedule :exec
UPDATE schedules
SET name = $2, scenario_id = $3, target_id = $4, cron = $5, timezone = $6, overrides = $7, env = $8,
    workers = $9, enabled = $10, note = $11, owner_id = $12, next_run_at = $13, updated_at = now()
WHERE id = $1
`

type UpdateScheduleParams struct {
	ID         uuid.UUID
	Name       string
	ScenarioID uuid.UUID
	TargetID   uuid.UUID
	Cron       string
	Timezone   string
	Overrides  json.RawMessage
	Env        json.RawMessage
	Workers    int32
	Enabled    bool
	Note       string
	OwnerID    *uuid.UUID
	NextRunAt  *time.Time
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error {
	_, err := q.db.Exec(ctx, updateSchedule,
		arg.ID,
		arg.Name,
		arg.ScenarioID,
		arg.TargetID,
		arg.Cron,
		arg.Timezone,
		arg.Overrides,
		arg.Env,
		arg.Workers,
		arg.Enabled,
		arg.Note,
		arg.OwnerID,
		arg.NextRunAt,
	)
	return err
}
