// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: settings.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteProjectRole = `-- name: DeleteProjectRole :execrows
DELETE FROM project_roles WHERE project_id = $1 AND user_id = $2
`

type DeleteProjectRoleParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) DeleteProjectRole(ctx context.Context, arg DeleteProjectRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectRole, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrgCaps = `-- name: GetOrgCaps :one
SELECT org_id, max_rate, max_vus, max_duration_s, updated_by, updated_at FROM org_caps WHERE org_id = $1
`

func (q *Queries) GetOrgCaps(ctx context.Context, orgID uuid.UUID) (OrgCap, error) {
	row := q.db.QueryRow(ctx, getOrgCaps, orgID)
	var i OrgCap
	err := row.Scan(
		&i.OrgID,
		&i.MaxRate,
		&i.MaxVus,
		&i.MaxDurationS,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectRole = `-- name: GetProjectRole :one
SELECT role FROM project_roles WHERE project_id = $1 AND user_id = $2
`

type GetProjectRoleParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetProjectRole(ctx context.Context, arg GetProjectRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getProjectRole, arg.ProjectID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getProjectSettings = `-- name: GetProjectSettings :one
SELECT project_id, max_rate, max_vus, max_duration_s, require_dry_run, updated_by, updated_at FROM project_settings WHERE project_id = $1
`

func (q *Queries) GetProjectSettings(ctx context.Context, projectID uuid.UUID) (ProjectSetting, error) {
	row := q.db.QueryRow(ctx, getProjectSettings, projectID)
	var i ProjectSetting
	err := row.Scan(
		&i.ProjectID,
		&i.MaxRate,
		&i.MaxVus,
		&i.MaxDurationS,
		&i.RequireDryRun,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectRoles = `-- name: ListProjectRoles :many
SELECT pr.user_id, pr.role, pr.created_at, u.email, u.name, m.role AS org_role
FROM project_roles pr
JOIN users u ON u.id = pr.user_id
JOIN projects p ON p.id = pr.project_id
LEFT JOIN memberships m ON m.org_id = p.org_id AND m.user_id = pr.user_id
WHERE pr.project_id = $1
ORDER BY u.email
`

type ListProjectRolesRow struct {
	UserID    uuid.UUID
	Role      string
	CreatedAt time.Time
	Email     string
	Name      string
	OrgRole   *string
}

func (q *Queries) ListProjectRoles(ctx context.Context, projectID uuid.UUID) ([]ListProjectRolesRow, error) {
	rows, err := q.db.Query(ctx, listProjectRoles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectRolesRow{}
	for rows.Next() {
		var i ListProjectRolesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
			&i.OrgRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProjectRoles = `-- name: ListUserProjectRoles :many
SELECT pr.project_id, pr.role FROM project_roles pr JOIN projects p ON p.id = pr.project_id
WHERE p.org_id = $1 AND pr.user_id = $2
`

type ListUserProjectRolesParams struct {
	OrgID  uuid.UUID
	UserID uuid.UUID
}

type ListUserProjectRolesRow struct {
	ProjectID uuid.UUID
	Role      string
}

// The caller's overrides across an organisation's projects.
func (q *Queries) ListUserProjectRoles(ctx context.Context, arg ListUserProjectRolesParams) ([]ListUserProjectRolesRow, error) {
	rows, err := q.db.Query(ctx, listUserProjectRoles, arg.OrgID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserProjectRolesRow{}
	for rows.Next() {
		var i ListUserProjectRolesRow
		if err := rows.Scan(&i.ProjectID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putOrgCaps = `-- name: PutOrgCaps :exec
INSERT INTO org_caps (org_id, max_rate, max_vus, max_duration_s, updated_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id) DO UPDATE
SET max_rate = EXCLUDED.max_rate, max_vus = EXCLUDED.max_vus, max_duration_s = EXCLUDED.max_duration_s,
    updated_by = EXCLUDED.updated_by, updated_at = now()
`

type PutOrgCapsParams struct {
	OrgID        uuid.UUID
	MaxRate      *float64
	MaxVus       *int32
	MaxDurationS *int32
	UpdatedBy    *uuid.UUID
}

func (q *Queries) PutOrgCaps(ctx context.Context, arg PutOrgCapsParams) error {
	_, err := q.db.Exec(ctx, putOrgCaps,
		arg.OrgID,
		arg.MaxRate,
		arg.MaxVus,
		arg.MaxDurationS,
		arg.UpdatedBy,
	)
	return err
}

const putProjectSettings = `-- name: PutProjectSettings :exec
INSERT INTO project_settings (project_id, max_rate, max_vus, max_duration_s, require_dry_run, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (project_id) DO UPDATE
SET max_rate = EXCLUDED.max_rate, max_vus = EXCLUDED.max_vus, max_duration_s = EXCLUDED.max_duration_s,
    require_dry_run = EXCLUDED.require_dry_run, updated_by = EXCLUDED.updated_by, updated_at = now()
`

type PutProjectSettingsParams struct {
	ProjectID     uuid.UUID
	MaxRate       *float64
	MaxVus        *int32
	MaxDurationS  *int32
	RequireDryRun bool
	UpdatedBy     *uuid.UUID
}

func (q *Queries) PutProjectSettings(ctx context.Context, arg PutProjectSettingsParams) error {
	_, err := q.db.Exec(ctx, putProjectSettings,
		arg.ProjectID,
		arg.MaxRate,
		arg.MaxVus,
		arg.MaxDurationS,
		arg.RequireDryRun,
		arg.UpdatedBy,
	)
	return err
}

const setProjectRole = `-- name: SetProjectRole :exec
INSERT INTO project_roles (project_id, user_id, role, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, user_id) DO UPDATE
SET role = EXCLUDED.role, created_by = EXCLUDED.created_by, created_at = now()
`

type SetProjectRoleParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedBy *uuid.UUID
}

func (q *Queries) SetProjectRole(ctx context.Context, arg SetProjectRoleParams) error {
	_, err := q.db.Exec(ctx, setProjectRole,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.CreatedBy,
	)
	return err
}
