import { Link } from '@tanstack/react-router';
import { CheckCircle2 } from 'lucide-react';
import { useState } from 'react';
import { useApproveAIJob, useScenario, useScenarios } from '@/api/queries';
import type { AIJob, AIJobApprove } from '@/api/types';
import { Confirm } from '@/components/dialog';
import {
  Button,
  Card,
  CardHeader,
  ErrorAlert,
  Field,
  Input,
  Notice,
  Select,
} from '@/components/ui';
import { relativeTime } from '@/lib/format';

/** Where an approved proposal was saved, with a link to the scenario. */
export function Approved({ job }: { job: AIJob }) {
  if (!job.approvedScenarioId) return null;
  return <ApprovedLink job={job} scenarioId={job.approvedScenarioId} />;
}

function ApprovedLink({ job, scenarioId }: { job: AIJob; scenarioId: string }) {
  const scenario = useScenario(scenarioId);
  const name = scenario.data?.name ?? 'the scenario';
  return (
    <Notice tone="pass" className="flex items-center gap-2">
      <CheckCircle2 className="size-4 shrink-0 text-pass" aria-hidden />
      <span>
        Approved {relativeTime(job.approvedAt)}: saved as{' '}
        <Link
          to="/projects/$projectId/scenarios/$scenarioId"
          params={{ projectId: job.projectId, scenarioId }}
          search={job.approvedVersion ? { version: job.approvedVersion } : {}}
          className="font-medium underline"
        >
          {name}
          {job.approvedVersion ? ` v${job.approvedVersion}` : ''}
        </Link>
        .
      </span>
    </Notice>
  );
}

/** Saves a finished job's proposal as a new scenario or a new version. */
export function ApprovePanel({ job }: { job: AIJob }) {
  const scenarios = useScenarios(job.projectId);
  const approve = useApproveAIJob(job);
  const [scenarioId, setScenarioId] = useState(job.scenarioId ?? '');
  const [message, setMessage] = useState('');
  const [confirming, setConfirming] = useState(false);
  const flagged = job.journeys.filter((j) => j.status === 'flagged').map((j) => j.name);
  const review = job.status === 'needs_review';

  const body = (allowUnvalidated: boolean): AIJobApprove => ({
    ...(scenarioId ? { scenarioId } : {}),
    ...(message.trim() ? { message: message.trim() } : {}),
    allowUnvalidated,
  });
  const target = scenarios.data?.find((s) => s.id === scenarioId);

  if (approve.data) {
    const { scenario, version } = approve.data;
    return (
      <Notice tone="pass" className="flex items-center gap-2">
        <CheckCircle2 className="size-4 shrink-0 text-pass" aria-hidden />
        <span>
          Saved as{' '}
          <Link
            to="/projects/$projectId/scenarios/$scenarioId"
            params={{ projectId: job.projectId, scenarioId: scenario.id }}
            search={{ version }}
            className="font-medium underline"
          >
            {scenario.name} v{version}
          </Link>
          .
        </span>
      </Notice>
    );
  }

  return (
    <Card>
      <CardHeader
        title="Approve"
        description="Nothing is saved until you approve. The proposal leaves target.baseURL out; runs take it from their target."
      />
      <div className="flex flex-col gap-3 px-4 py-3">
        {review && (
          <Notice tone="warn">
            {flagged.length > 0 ? (
              <>
                {flagged.length === 1 ? 'Journey' : 'Journeys'}{' '}
                <span className="font-medium">{flagged.join(', ')}</span> did not pass the dry run.
                Check the traces below before you approve.
              </>
            ) : (
              'Some journeys were not validated. Check them before you approve.'
            )}
          </Notice>
        )}
        <div className="grid gap-3 sm:grid-cols-2">
          <Field
            label="Save as"
            hint={
              target
                ? `Adds version ${target.latestVersion.version + 1} of ${target.name}.`
                : 'Creates a scenario named after the proposal.'
            }
          >
            {(p) => (
              <Select {...p} value={scenarioId} onChange={(e) => setScenarioId(e.target.value)}>
                <option value="">A new scenario</option>
                {scenarios.data?.map((s) => (
                  <option key={s.id} value={s.id}>
                    New version of {s.name}
                  </option>
                ))}
              </Select>
            )}
          </Field>
          <Field label="Message" hint="Optional. Shown in the scenario's history.">
            {(p) => (
              <Input
                {...p}
                maxLength={500}
                placeholder={`generated by AI job ${job.id.slice(0, 8)}`}
                value={message}
                onChange={(e) => setMessage(e.target.value)}
              />
            )}
          </Field>
        </div>
        <ErrorAlert error={confirming ? null : approve.error} />
        <div className="flex justify-end">
          <Button
            variant="primary"
            loading={approve.isPending && !confirming}
            onClick={() => {
              if (review) setConfirming(true);
              else approve.mutate(body(false));
            }}
          >
            {review ? 'Approve with flagged journeys…' : 'Approve and save'}
          </Button>
        </div>
      </div>
      <Confirm
        open={confirming}
        onOpenChange={setConfirming}
        title="Approve without a passing dry run?"
        description={
          <>
            {flagged.length > 0 ? (
              <>
                <span className="font-medium text-fg">{flagged.join(', ')}</span> failed the dry run
                even after repair.
              </>
            ) : (
              'Some journeys were not validated.'
            )}{' '}
            The scenario is saved as proposed. Fix the flagged journeys in the editor before you run
            it under load.
          </>
        }
        confirmLabel="Approve anyway"
        onConfirm={() => approve.mutateAsync(body(true))}
      />
    </Card>
  );
}
