import { Check, Copy, Monitor, Moon, Sun } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Button } from './ui';
import * as Tooltip from '@radix-ui/react-tooltip';
import type { ReactNode } from 'react';

/** The Stampede mark: the block-art bull (generated by brand/build.py). */
export function Mark({ className = 'h-6 w-auto' }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 13 10"
      className={className}
      role="img"
      aria-label="Stampede"
      shapeRendering="crispEdges"
    >
      <path
        fill="var(--accent)"
        d="M0 0h1v1h-1zM12 0h1v1h-1zM0 1h2v1h-2zM11 1h2v1h-2zM1 2h11v1h-11zM2 3h9v1h-9zM2 4h2v1h-2zM5 4h3v1h-3zM9 4h2v1h-2zM2 5h9v1h-9zM3 6h7v1h-7zM3 7h1v1h-1zM5 7h3v1h-3zM9 7h1v1h-1zM3 8h7v1h-7zM3 9h2v1h-2zM8 9h2v1h-2z"
      />
    </svg>
  );
}

export function CopyButton({ value, label = 'Copy' }: { value: string; label?: string }) {
  const [copied, setCopied] = useState(false);
  useEffect(() => {
    if (!copied) return;
    const t = setTimeout(() => setCopied(false), 1500);
    return () => clearTimeout(t);
  }, [copied]);
  return (
    <Button
      size="sm"
      onClick={() => {
        void navigator.clipboard?.writeText(value).then(() => setCopied(true));
      }}
      aria-label={copied ? 'Copied' : label}
    >
      {copied ? (
        <Check className="size-3.5 text-pass" aria-hidden />
      ) : (
        <Copy className="size-3.5" aria-hidden />
      )}
      {copied ? 'Copied' : label}
    </Button>
  );
}

export function Tip({ content, children }: { content: ReactNode; children: ReactNode }) {
  return (
    <Tooltip.Provider delayDuration={300}>
      <Tooltip.Root>
        <Tooltip.Trigger asChild>{children}</Tooltip.Trigger>
        <Tooltip.Portal>
          <Tooltip.Content
            sideOffset={6}
            className="z-[70] max-w-xs rounded-md border border-line bg-surface px-2 py-1 text-xs text-fg shadow-md"
          >
            {content}
          </Tooltip.Content>
        </Tooltip.Portal>
      </Tooltip.Root>
    </Tooltip.Provider>
  );
}

// ---------------------------------------------------------------- Theme

export type ThemePref = 'system' | 'light' | 'dark';
const THEME_KEY = 'stampede.theme';

function readPref(): ThemePref {
  try {
    const v = localStorage.getItem(THEME_KEY);
    return v === 'light' || v === 'dark' ? v : 'system';
  } catch {
    return 'system';
  }
}

function applyPref(p: ThemePref) {
  const root = document.documentElement;
  if (p === 'system') delete root.dataset.theme;
  else root.dataset.theme = p;
  try {
    if (p === 'system') localStorage.removeItem(THEME_KEY);
    else localStorage.setItem(THEME_KEY, p);
  } catch {
    /* storage unavailable */
  }
  window.dispatchEvent(new Event('stampede-theme'));
}

/** Whether the effective theme is dark, updating on OS or user changes. */
export function useIsDark(): boolean {
  const compute = () => {
    const t = document.documentElement.dataset.theme;
    if (t === 'dark') return true;
    if (t === 'light') return false;
    return window.matchMedia?.('(prefers-color-scheme: dark)').matches ?? false;
  };
  const [dark, setDark] = useState(compute);
  useEffect(() => {
    const mq = window.matchMedia?.('(prefers-color-scheme: dark)');
    const update = () => setDark(compute());
    mq?.addEventListener('change', update);
    window.addEventListener('stampede-theme', update);
    return () => {
      mq?.removeEventListener('change', update);
      window.removeEventListener('stampede-theme', update);
    };
  }, []);
  return dark;
}

export function ThemeToggle() {
  const [pref, setPref] = useState<ThemePref>(readPref);
  const next: Record<ThemePref, ThemePref> = { system: 'light', light: 'dark', dark: 'system' };
  const Icon = pref === 'system' ? Monitor : pref === 'light' ? Sun : Moon;
  const label = `Theme: ${pref}. Switch to ${next[pref]}.`;
  return (
    <Tip content={label}>
      <Button
        variant="ghost"
        size="sm"
        aria-label={label}
        className="px-1.5"
        onClick={() => {
          const n = next[pref];
          setPref(n);
          applyPref(n);
        }}
      >
        <Icon className="size-4" aria-hidden />
      </Button>
    </Tip>
  );
}

/** Reads a CSS custom property from the root element (for chart colours). */
export function cssVar(name: string): string {
  return getComputedStyle(document.documentElement).getPropertyValue(name).trim();
}
